apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: coredns-proxy-config
    files:
      - Corefile
commonLabels:
  app: coredns-proxy
images:
  - name: coredns/coredns
    newTag: "1.11.3"
