apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coredns-proxy-tailscale-state
  namespace: infrastructure
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-csi
