apiVersion: v1
kind: Secret
metadata:
  name: issuer-secrets
  namespace: infrastructure
type: Opaque
stringData:
  digitaloceanDnsPat: ENC[AES256_GCM,data:6Tgs/4cqj+wWnIeOtwKVAC637Qbd4V8iVt0YtPJ6bvIr629Iow4eC74+J2KGVuInXRh//gR54Laax6CcdMT/zx7lFJGS/x4=,iv:OYNnSGEBIZ+Js7uFVQVlxnlUbAaC41KHux+yt5hg06w=,tag:PlILadeXaUo4QqiqzChUeA==,type:str]
sops:
  azure_kv:
    - created_at: "2026-10-09T05:24:43Z"
      enc: jvR7rUE-yleiybO65JjC9H0XdO09i6hDUyRV6RcooKFGXUg93XNIZjCKtdBDJsxd794ZEkNRlUcK9v8GZKRLRYt11-w9OqEJsMKmCPRBSTBFVYKJKQv7Uy_XeyXYPH1_6NhLPkyQL7nd8QozL2RNTgGcSdVX2dyJJtZmA0Idmyt8zPk_-_xz7OdIsdrUX_aXkht2BH9G3kOKj9ewPGFuQ269V7SYB7Z3IkvATPGBQoNPkk3Gx2WY_o3LRZsObne_P-bZYIBSXCFZ0KfMwFYPazk4C1HqbGmMPDGCEk8jHUNuk6uL_j06-Iflj_Suav8eOwyC3sOv2E78yiDC3kkTwg69dVPAjRzkp2axAjn0AiX2ravIAy6UoDIz61QkFKVNfXpLxhphUyA4qOWQ4t1HBocCyU5gT4b5GrCKz4iin4U6_iqHL-NfS7y6Za9Ugh5_9PmomeGd-ujSDZxeQBlsqe4TFJC4-XloR6TsMqS4URR6GwP__jsQEjaC8k7m6IyigyKZB-yDu25Pxn-pgG_pX1fLFG5awXpYjVl--dw6qnh3Azdi1w0GeIJzgh8xhyReYa9i_dkrlpDr05fKTEt6HIFQ9NAUx01vKZ-aCTen8DvUaI9PvI54cREOP5YAK5z40kWFmK4D2iTIkTjlmFF2VHlAXypmRBfxxFslvQHIxoo
      name: sops-administrators-key
      vault_url: https://sops-administrators.vault.azure.net
      version: 37bc81e975ea4a2194985560d066d52d
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T05:24:45Z"
  mac: ENC[AES256_GCM,data:fsWT4Kw35SNvIrIBwrBZkfUHhIu5JRqV30E7wTN1S7lAvF6zzpYXYKScgXXTeKugrviE72H+snixw0g6kaKvwNmfQYYmcTFIlfgjMwbDSGzvIUQoAMWXMSVV5KZEflQU0A/iiND+3l5/p46SWtC5mPXIVS+bl7pSLvqjcDOxsb4=,iv:trfboxkjTKSXOAtHgj/K0JuBxG0AuWRUfVE2yOw8QQs=,tag:3Vqg7D9jDYmMSUcZqBT9fA==,type:str]
  version: 3.13.3
