apiVersion: v1
kind: Secret
metadata:
  name: issuer-secrets
  namespace: infrastructure
type: Opaque
stringData:
  digitaloceanDnsPat: ENC[AES256_GCM,data:LPi/JbdirnIu4H/RI1ItiW6vMzVDwVE0BNZ3j9nd8nDHcq2dOhoNjT+vsWY5NPXvSQEAxQKXIS/640TiNMnrD3WPfocQm10=,iv:OYNnSGEBIZ+Js7uFVQVlxnlUbAaC41KHux+yt5hg06w=,tag:z8GIuzvXJ575yeDtykgYwA==,type:str]
sops:
  azure_kv:
    - created_at: "2026-09-10T08:03:06Z"
      enc: lLlVg1Gr-mhcd6rGIEt2YToPpOciYO7yz7dh9_88qE_A19dLhDTyS9si3717t_c36nbrLOIwFBMZZ_GUf_wd1IBSgU3p-iLFH5EHM-mVJuvWrJ40xhbx_OCIcJXyxQTlsg1Anf-Xj-_dnAnluWGyVz2YbtyYACk8i5K4-CZmq-ERFl5hH4OfQV-rlALOihpJL9TITHReQIvQ9GRscSBQ0c3axJ3XWTxqreOuVuNllOU-HeyadiHgQFAFU1VptXGuU3lF83YVoyrScUV1GBbym2BSdpB3PyoFilr3cnRGBNxXzAQfeX3-GLDm4KEJ2DcdgHSVIplhp8J5j6td2-2Y5g
      name: sops-key
      vault_url: https://sops-master.vault.azure.net
      version: 90784f2986de4514934b4d1f682d3e59
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-10T14:52:31Z"
  mac: ENC[AES256_GCM,data:yQ+cv+KNE4uZ6fd3J4tIk3J+4iInqkFyLsImgc1kbrp43COWL5V/Wi2W2asjAHl6/swzwJPicM551TaT1AChYHarcmZJ7NgPxmpaOB0p3OWoRl/3Ha5WvZOpDgMeCrLotGKaBsMpR0ObUgHUH4QX84D9ek+hBFZyobbs0lHR0/0=,iv:IjBBQbPW1S5krXxb77BEnuvgdTiZFx9f2Gr18Zfg8Mw=,tag:jfA0lI1LOO5oeZ9RjwqPlg==,type:str]
  version: 3.13.3
