# shared defaults live in base/base/patchats/application.yaml

server:
  url: https://patchats.patinanetwork.org
# management:
#   endpoint:
#     env:
#       # /actuator/* is pwd protected so this is ok
#       show-values: "always"
