apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - state.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: proxy-coredns-config
    files:
      - Corefile
commonLabels:
  app: proxy-coredns

images:
  - name: coredns/coredns
    newTag: "1.11.3" # update me to change version
  - name: tailscale/tailscale
    newTag: "v1.102.3" # update me to change version
