apiVersion: v1
kind: Service
metadata:
  name: proxy-coredns
  namespace: infrastructure
spec:
  type: ClusterIP
  selector:
    app: proxy-coredns
  ports:
    - { name: dns, port: 53, targetPort: 53, protocol: UDP }
    - { name: dns-tcp, port: 53, targetPort: 53, protocol: TCP }
