apiVersion: apps/v1
kind: Deployment
metadata:
  name: codebloom-standup-bot
spec:
  template:
    spec:
      nodeSelector:
        agentpool: prodpoolv1
      tolerations:
        - key: workload
          operator: Equal
          value: production
          effect: NoSchedule
      containers:
        - name: codebloom-standup-bot
          env:
            - name: ENVIRONMENT
              value: production
          envFrom:
            - secretRef:
                name: codebloom-standup-bot-production-secrets
