apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ../../base/codebloom-standup-bot
  - secrets.yaml
patches:
  - path: deployment-patch.yaml
commonLabels:
  app: codebloom-standup-bot
  environment: production
images:
  - name: patinanetwork/codebloom-standup-bot-arm
    newTag: 7c75942

replacements:
  - source:
      kind: Deployment
      name: codebloom-standup-bot
      fieldPath: spec.template.spec.containers.[name=codebloom-standup-bot].image
      options:
        delimiter: ":"
        index: 1
    targets:
      - select:
          kind: Deployment
          name: codebloom-standup-bot
        fieldPaths:
          - spec.template.spec.containers.[name=codebloom-standup-bot].env.[name=VERSION].value
          - spec.template.metadata.labels.version
