apiVersion: v1
kind: Secret
metadata:
  name: codebloom-standup-bot-production-secrets
type: Opaque
stringData:
  DISCORD_CLIENT_ID: ENC[AES256_GCM,data:XQ2mPGOjzoQbU0GyS9dAR/D6iQ==,iv:iuASsN+MsHVbQu57mkGifXV/gYp3olfA8QXgVJFvmXI=,tag:o8KL4O+RnsvxrOdcdzzkuw==,type:str]
  DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:on9F/SRNwFXSgCyg3WZFKFMe3n4wPS2TxVoxursj7VY=,iv:SCLf0mOQ+fa+4I+lRVDyvc3DsCEJaeAsoN5F0e6+bhM=,tag:qCC5rIJkID45JtTDJdlvbg==,type:str]
  DISCORD_TOKEN: ENC[AES256_GCM,data:XdL772Vb+P+UrILlH+clighDk3+zoBQauDUiCSlaMkJJi7IhrvwfEk5dHmoZ6P6wTgg7GGKp2TGxwv6L4c8PfRXlLcPDy42I,iv:RIt7NQkErSIW8hh2qvy0zo21Yji71n/hk94GdkAsjVU=,tag:qE63Wr9bpk4ZpibXYRR/AA==,type:str]
  DISCORD_GUILD_ID: ENC[AES256_GCM,data:wDZNFiYFZIdnsz4n1+VlLXzM8Q==,iv:dngPhi+m8dDXRJPJFLKzZ6/E8n8wjh1seylG2C+1x30=,tag:vEboqgBi66iIaPZnnBIMUg==,type:str]
  DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:ENMaDSO+AuKABHuhWVGw5j/ZpQ==,iv:5LFHFyPltjl0F74sQ9hvnI/O6FEbEjIpokgWpeoRazw=,tag:9gXcTffFe0v5cIoH3buymA==,type:str]
  REDIS_URI: ENC[AES256_GCM,data:Ark9zPfIfoQybmbQ59Yf99ej31pI1706wxfcS6wqa52SiXIQbLg8eYQTRYt8kS5iCtDrViMTJiqNgJzhXoEHUFVZuYwJtV1sbvr3F8yxtLvJN/UFgLJxfjwRVu2p5UQ=,iv:daohMv/5TtkP8DYCY08dqUJuGYoRkFjS4QWF0a+PATk=,tag:+vtEQN8Qg+IpJc7e8sGeqg==,type:str]
sops:
  azure_kv:
    - created_at: "2026-04-27T06:01:08Z"
      enc: L1bRDOaiwm7fRz7yHWJPrCUGKO4VzMTxbkK2MQxMUDi5sNrBr-Gbe8XDAayIIcp7ZQBJlTLwGHvwHfpjV0Lwf2yQHZL9vSGLFVg5WZofvMUPvD9wlNB4_ESM3DqzQsIc6HIzJCT4Y8ZnDAnEj6sjnoj0ytGudk-qF6VHlbj_gLUSu7Irt7U8N5TiyCPPiMOQF62Fb2S6_dLyryKUaeGRotqkrMBrmIe2TsqBaAQuEzXk1AslT8JOf2oBxlXayv86YIU2hr-ZX-gc7OruJqoe9jOSQbeWq3BaUpQSPvrVBqRZuP6gplwOiDsC1Eh-vkGutoOnSavwUp8X2NKd8Xi2Mg
      name: sops-key
      vault_url: https://sops-master.vault.azure.net
      version: 90784f2986de4514934b4d1f682d3e59
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-20T22:35:24Z"
  mac: ENC[AES256_GCM,data:Y15z/5e+1ga5vzbfZ9FV/J+4M3jmNJMqGt5Lk0CrfkEsb5eGhhqFoo79G9DHUaNk1/R51InY+JUG7GFmBiDUxhW4BS9NLLeWOXP7DY9eb9CCTqo4J0KiIX2mAcR6clmgLoQCBMepdW2NhloBc36J8s9QDe46jwO/S+weCFuA3cg=,iv:zduC8xNqKEcLuYEyjzxTjI6Fdr6gihszadL7hi3ng5Q=,tag:YOguWNBYycb2rj4WNEmmpA==,type:str]
  version: 3.12.1
