apiVersion: v1
kind: Secret
metadata:
    name: codebloom-standup-bot-production-secrets
type: Opaque
stringData:
    DISCORD_CLIENT_ID: ENC[AES256_GCM,data:XQ2mPGOjzoQbU0GyS9dAR/D6iQ==,iv:iuASsN+MsHVbQu57mkGifXV/gYp3olfA8QXgVJFvmXI=,tag:o8KL4O+RnsvxrOdcdzzkuw==,type:str]
    DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:on9F/SRNwFXSgCyg3WZFKFMe3n4wPS2TxVoxursj7VY=,iv:SCLf0mOQ+fa+4I+lRVDyvc3DsCEJaeAsoN5F0e6+bhM=,tag:qCC5rIJkID45JtTDJdlvbg==,type:str]
    DISCORD_TOKEN: ENC[AES256_GCM,data:XdL772Vb+P+UrILlH+clighDk3+zoBQauDUiCSlaMkJJi7IhrvwfEk5dHmoZ6P6wTgg7GGKp2TGxwv6L4c8PfRXlLcPDy42I,iv:RIt7NQkErSIW8hh2qvy0zo21Yji71n/hk94GdkAsjVU=,tag:qE63Wr9bpk4ZpibXYRR/AA==,type:str]
    DISCORD_GUILD_ID: ENC[AES256_GCM,data:pJqHQC4qleVqg2ufZiIsGejb9g==,iv:ztFrmoqFWY8qG/ioY1XCtdwHDyiVqyThAUrB/2rMQMM=,tag:/dYb+GSWys/gFY0yuw1sJg==,type:str]
    DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:UXwpiKIE7AjuvF9eKzgihjbTQQ==,iv:u1NW60gwKzib7xUaJpMaWfJiQr8AZJIcMiTVU1KutJI=,tag:wrFNn3nODGB/emseO09Jng==,type:str]
    REDIS_URI: ENC[AES256_GCM,data:Ark9zPfIfoQybmbQ59Yf99ej31pI1706wxfcS6wqa52SiXIQbLg8eYQTRYt8kS5iCtDrViMTJiqNgJzhXoEHUFVZuYwJtV1sbvr3F8yxtLvJN/UFgLJxfjwRVu2p5UQ=,iv:daohMv/5TtkP8DYCY08dqUJuGYoRkFjS4QWF0a+PATk=,tag:+vtEQN8Qg+IpJc7e8sGeqg==,type:str]
sops:
    azure_kv:
        - created_at: "2026-04-27T06:01:08Z"
          enc: L1bRDOaiwm7fRz7yHWJPrCUGKO4VzMTxbkK2MQxMUDi5sNrBr-Gbe8XDAayIIcp7ZQBJlTLwGHvwHfpjV0Lwf2yQHZL9vSGLFVg5WZofvMUPvD9wlNB4_ESM3DqzQsIc6HIzJCT4Y8ZnDAnEj6sjnoj0ytGudk-qF6VHlbj_gLUSu7Irt7U8N5TiyCPPiMOQF62Fb2S6_dLyryKUaeGRotqkrMBrmIe2TsqBaAQuEzXk1AslT8JOf2oBxlXayv86YIU2hr-ZX-gc7OruJqoe9jOSQbeWq3BaUpQSPvrVBqRZuP6gplwOiDsC1Eh-vkGutoOnSavwUp8X2NKd8Xi2Mg
          name: sops-key
          vault_url: https://sops-master.vault.azure.net
          version: 90784f2986de4514934b4d1f682d3e59
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T15:53:22Z"
    mac: ENC[AES256_GCM,data:gBByB/u05HXR/UwjGCY5BtMeuq5MgIUo7O1L7qkA7HlOJ49tE+qjTZvyXNJTDKyj/KrOLbdQar2gWZkcy8WZ4XOU6LTiOer+8lSLrFxUTK3tw5zBMzlJc5sMbpnHOdg/03o58h8wSSg/9ynZgzq0UQMTKL4+Efrb8GfJQqip67M=,iv:+VjlrFGcxyz420ZGqewKY0QNNr8k1zMELzNRaPolJxk=,tag:slpmmHSUXgjCPHi/SnxTcQ==,type:str]
    version: 3.12.1
