apiVersion: v1
kind: Secret
metadata:
  name: headscale-secrets
  namespace: infrastructure
type: Opaque
stringData:
  databasePassword: ENC[AES256_GCM,data:UrGP6vw73nzA/DwxY0zBfKRO4we0XqKN3PfSgY+zIQI=,iv:EDL4RceCUAd0enYNxYK3xFmeaH9dRpNr395uBHB6S0I=,tag:hLlMeAacUfpLsPUqa7oVRA==,type:str]
sops:
  azure_kv:
    - created_at: "2026-09-09T07:24:42Z"
      enc: V5TUKdPlX8ssq2S1rkAYCtiJoG-_EYz0hWNT79e0_rrykSMWugDU9k9pn9U2UQZQ3FiOluQhtB168Z2y71qjbqf3lLprjC6n35cRxEeTxpYp2YcLs21rImsAKXJSkinuvPNr4uy4kUrv1POYhgUtoHjkNmBgGGtjorZThP1h5RGBLBaL06NBFIRIPsMTEXY2pCI5pEql2QOYl0ANjMzgRY8oPkEOstLGSiOs8PhSV8aAyu-W3PY_AiR01OgSAa3Rwpil9Q3SykWoacnj-R64Z5xf6rXNw01tGqriuNt4vTFWG61mqfQZRvxSasrQt1GckXuPFiXKFuX6Xx4M0yyIgg
      name: sops-key
      vault_url: https://sops-master.vault.azure.net
      version: 90784f2986de4514934b4d1f682d3e59
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-09T17:44:08Z"
  mac: ENC[AES256_GCM,data:8jfZAmV7EDTcuK1gV2Bi+eVJ0cWul1JoG943mFsVXWDr+SK+n91IGsF+hKQa3E+0XPX6tf6D1+6p/R91A6FWhHl77+JqImkJIG1hT5J9V9eJFLvsZmbU7tItYM/GteiNVurHO6yyrYxxwgEXYQo/5pzKzjyUky5QkjTykLMK/i0=,iv:grY34ln9HyPwm5xdnnd6R3cnoiXzrA3W4hgiQ3RTyXY=,tag:FwDLGky8gW5RbJIAb7b3Hg==,type:str]
  version: 3.13.3
