apiVersion: v1
kind: Secret
metadata:
  name: headscale-secrets
  namespace: infrastructure
type: Opaque
stringData:
  databasePassword: ENC[AES256_GCM,data:lttfNMXVn4I9xFyCOdSdHpkfvUTEoDkxyqX1FVFd3NA=,iv:TirdtsrGXkqs4EjbKz9K8aMUPYBT27lZJj2z4aSqZ6Q=,tag:MA9gtajbGQTgE31TGAM0XQ==,type:str]
  oidcClientSecret: ENC[AES256_GCM,data:igVcd0VbMESFTSWdUexXH/84iw6FQqnXVMEeH6hi9T8vUahFLX11YQ==,iv:Lma7GDAXlE80Tn6MB1FMDa/XSDQ2N6GV3hmkG0rQYQo=,tag:AgeE3KB4rvEDyPU660mcOw==,type:str]
sops:
  azure_kv:
    - created_at: "2026-10-09T05:20:17Z"
      enc: Utw4AI6VWjkGfXwZjwb36rcyBGMsFfzuRHgT7fizE9kQg-qhCVbJw2GGCQ6ZWK5GPE1KLmjG4MiXbQiRMa5IABbGQezUVYkVvmZRt2H4ZA7GF-b4xyRexNLYwaLA_-sFMlP3xQHgO0TlgVR3YifQFirzgX9He1wELTq8nlJO5s3BcWmUxidoys3SOUK6g7fuuOhF0Y9bdCNTzSQixTgpjKdlgZnA6XcF1GJd76uRRPlfaRaz205Rx5EJVtqqRDwi9v1CGrQPeqarCTAeiQJIl81q8tNxjL1M_qnp_zTs8F2vw35DAXEU-Qz8n20S2QTV6ry09SQ5s3scGVyPytCGkrRldfsVT5rC7Z8i4KPSv55303Xl8S6S9c4h9MKlYFTrQJdAE64iPq3DRSc2ttrLN-7jDlTQliTcnnwqH9DnA2NZ-W-rMYyl9i-ze-5r0cuSE2O3bs7H4agAkKYxaYKKmhvuZoFpxMo5KxPXXr4cLI2Z0Ox_0AClf6n_oo6Hw_3HFM3ZSWzwGM9RZL2QkKgzHKXmwbYFSrP46shFy_tAXnfzDfte_15HBa7IlikGIGK2TIOdmT5p5nBisocrlwMBVqL7LClcA6P3_r_C6hTiZfQAdgt0j1vRBUksDEJqFXeupTUNcJUFSatHqqTbptO5gUxOcVamkVoYRDfpPyhI8y0
      name: sops-administrators-key
      vault_url: https://sops-administrators.vault.azure.net
      version: 37bc81e975ea4a2194985560d066d52d
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T05:20:18Z"
  mac: ENC[AES256_GCM,data:wyTO0kXX1Vf283OS5KsIBuFywlY8Rb5yhwtnDEuStFpevVOxDmasV1f+fuVm9LMSibQggPfHqG0oQ8qs677Uos9zhx53zrmPDxxNb6sE6QZIQOVPMPSP2b5Yu6z8iz32MBhb3jqjzW6Z/2NmejP3GgB2148N2Fd7DcCNsKQpJZY=,iv:uiei5ZpbnfehYfftSEbySjia4g8FEpkAuZv8v5nVAKk=,tag:lhQMrd5bqOgNeR1DoBZjkw==,type:str]
  version: 3.13.3
