apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: headscale-traefik-internal-infrastructure
  namespace: flux-system
spec:
  interval: 10m
  path: ./base/infrastructure/headscale/traefik-internal
  dependsOn:
    - name: traefik-infrastructure
    - name: headscale-tailscale-authkey-infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: infrastructure
