apiVersion: v1
kind: Secret
metadata:
  name: basicauth-secret
  namespace: production
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:7312Av5u,iv:aJ1yyT4yOISfqqAmJfJ9K7roolW8F6meWmOM6UIjtAI=,tag:POybQerqlQTMaVzcI1a/DQ==,type:str]
  #ENC[AES256_GCM,data:bKRC8R2aCL964uHRTCkS33L7wjxXPtICyPJVHJJhz2Ez1s5NLHwlWhciUTN+7An4VxJwr45rI4tKEWq/J/0Ebw==,iv:fosDLT/JZlepWk8R7V3elQ4ulDVNXOKaW2y2FInsJLc=,tag:IuONc3y1FObAhS3NV6oPdQ==,type:comment]
  password: ENC[AES256_GCM,data:FsAc/PAmnM3FwmZT3y/+ttGKuIQ27lsoUytjsRsyja4VAJBNmKNjU3iiu5K9uortcStGnmpyRTfzSzIkRGS1kQ==,iv:Ypvn/5Guw9tvHFSp0PIzNkRrDrQeAVfnBt2TpqD+5Wk=,tag:SJRuNgXPaEkOYQzuheaEvQ==,type:str]
sops:
  azure_kv:
    - created_at: "2026-07-29T03:35:20Z"
      enc: sRbanflOCbQV349qJvsHjc_Ro3ILmyU2Jqnm3dI7_v6zShSYJPS3FETUzCcGOotoEBuyaskXVWwFD8VlPWwuoNd4ucER1lRar0f8VPuqZ_9MC4ujQCHOe0lv-R9jCELrxpdeSEMJgxYeWKMyyCwI6cqFl_l3Pd_4kSTVIfWAaj_0_EkFfoRiCV6e2nUkiR2KG7fSDrxPs5QtPH1syFz50oAcsurNp_tPcmEuGTyOhqRPBvS1HcxVGMV6h_XrWhhDYDJCRbANI6tUGulwmkFR9DzwbfKd2bvUNY6Q4hkU2SO9aNS7CppNivRlq9WqOumvKv1nX6Le1oa6TSj3WXxbcw
      name: sops-key
      vault_url: https://sops-master.vault.azure.net
      version: 90784f2986de4514934b4d1f682d3e59
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T03:35:33Z"
  mac: ENC[AES256_GCM,data:PViqwvWzWWFsI15Wnr/0dbAHwPRBcD3dcLKP/NYtgozeqrkxM9Js+cGmQIDxB9FsGMMpwDwKlWmHtsWvMZ1D7i8Wcq4XAy4BOKbn55e99BUYiJDalwYhTRPNgoqUTM0Q4JBLIRwUr1YfpEYxK15E18dxRG3T0mFfe+/fUpqZ03k=,iv:AJUpDShGicamBFNsPOmvo3b7b2A7lorYoQ/aJHAKU1o=,tag:FcjPZCErQa29rxelC1ohlA==,type:str]
  version: 3.13.3
