apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base/docs
  - certificate-vpn.yaml
  - ingress-vpn.yaml
patches:
  - path: deployment-patch.yaml
commonLabels:
  app: docs
  environment: staging
images:
  - name: patinanetwork/docs-arm
    newTag: "staging-48d67f5f" # update me to change version

replacements:
  - source:
      kind: Deployment
      name: docs
      fieldPath: spec.template.spec.containers.[name=docs].image
      options:
        delimiter: ":"
        index: 1
    targets:
      - select:
          kind: Deployment
          name: docs
        fieldPaths:
          - spec.template.spec.containers.[name=docs].env.[name=VERSION].value
          - spec.template.metadata.labels.version
