apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-client-rust
spec:
  template:
    spec:
      nodeSelector:
        agentpool: prodpoolv1
      tolerations:
        - key: workload
          operator: Equal
          value: production
          effect: NoSchedule
      containers:
        - name: hello-world-client-rust
          env:
            - name: ENVIRONMENT
              value: production
            - name: HELLO_WORLD_CLIENT_URLS
              value: https://hello-world-client-go.vpn.patinanetwork.org,https://hello-world-client-java.vpn.patinanetwork.org
