apiVersion: v1
kind: Secret
metadata:
  name: basicauth-secret
  namespace: staging
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:AwJRPZLx,iv:ggUhdKsPZtGMTa1a3V7iCMyXMtVGfGDX1IAFqUahq7s=,tag:TBeZ4S+6gGXu7DOHeKSoLg==,type:str]
  #ENC[AES256_GCM,data:XNFqrg+GTvf71GVxKoKqNUnHwPelKikfJOmn1ZCyjiihQvnmTMkzkE7PScbLOHxZSH+rE8shRSUu/ZQ7ERr1gA==,iv:2eBZ+BOhXek/FcxsXy0J8vpww1YiuUXL1OGb099OR3Y=,tag:ZGZ11cnD8rcuG2tfxR/D7g==,type:comment]
  password: ENC[AES256_GCM,data:z8VqWYl+JolSbC+7vh2IrfXpTxP6UGiFfdPFfe3e9TNBKRpUywUzoPX+8z850R5za1d/gGgqa6+O30uYqXVXCg==,iv:irAKEUG+22lSxe5t1iUoyfTdXwd4kDLub8oTnZ9rsgQ=,tag:04PLNGzHpu/FTxxOd8l3xw==,type:str]
sops:
  azure_kv:
    - vault_url: https://sops-master.vault.azure.net
      name: sops-key
      version: 90784f2986de4514934b4d1f682d3e59
      created_at: "2026-05-18T07:45:56Z"
      enc: u-1b6atB9cickwXIcX8oS1-6ImrWE9kzZbYSKJauXScn_WPvZpeMIFz6WrgTXdwQXLb9zrmREsPdEVhVHwgXhLTCTHZCA5Ci_m5ohB_6UIZ9p8hyw07kt1u_850JQeRPcTVWtkC7zKuLQYiTZgbEH6SpptOeFdwDGO40kmiZY755IvORwRqIl_-QGQWfvrAgLwayVXwdeg_BRVxo4DcTc2ow8mLUKxEdaidTd2kZUipZMAL1JMKlGULP9ZZHxZyG-LDJTXMa5FaGFF0V5juUqROhfaUf6E2tdrp6omixoZd2hq0ohj--pzUxRnE7HzgwRzbIr5-LjfYsS1CEMQuP5g
  lastmodified: "2026-05-18T07:45:56Z"
  mac: ENC[AES256_GCM,data:421P+Yk6AN/faofHTeWwWZD8lUusIjgw2dGK7ZSnEVeAWkP7XyZgVt3QC7+0c/Cbx7q+NTgC2AG1rpgA5TjIZEt55988HZxFQMBbJBFnkZKFzy+oDuDPcIrgz9xi4SCUjVtUovnsOff0iq1zlYik820RIqmQAZTlr/nRKK2y+Mk=,iv:xkd2xjuRvp11KM2YLT01izen0FM/X67yt8sWkI0xs70=,tag:/TfOoQDcLCMktrQmYp4ZLQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
