apiVersion: v1
kind: Secret
metadata:
  name: basicauth-secret
  namespace: staging
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:AwJRPZLx,iv:ggUhdKsPZtGMTa1a3V7iCMyXMtVGfGDX1IAFqUahq7s=,tag:TBeZ4S+6gGXu7DOHeKSoLg==,type:str]
  #ENC[AES256_GCM,data:XNFqrg+GTvf71GVxKoKqNUnHwPelKikfJOmn1ZCyjiihQvnmTMkzkE7PScbLOHxZSH+rE8shRSUu/ZQ7ERr1gA==,iv:2eBZ+BOhXek/FcxsXy0J8vpww1YiuUXL1OGb099OR3Y=,tag:ZGZ11cnD8rcuG2tfxR/D7g==,type:comment]
  password: ENC[AES256_GCM,data:3cS+9yeXw4nrFUMUi8QMr34vHQ5VAqTCfS+W1o6u4nGCaIajFdtgq7UWCkcIgSp77v4Eh/+9fpAtNkupTDIukQ==,iv:crcZsZ2DPdGXVGn/HBLwYy0WPsEGpUnXNjxN80Cjb0o=,tag:3DwzqnRmsj4UwsMDKXC/vg==,type:str]
sops:
  azure_kv:
    - created_at: "2026-05-18T07:45:56Z"
      enc: u-1b6atB9cickwXIcX8oS1-6ImrWE9kzZbYSKJauXScn_WPvZpeMIFz6WrgTXdwQXLb9zrmREsPdEVhVHwgXhLTCTHZCA5Ci_m5ohB_6UIZ9p8hyw07kt1u_850JQeRPcTVWtkC7zKuLQYiTZgbEH6SpptOeFdwDGO40kmiZY755IvORwRqIl_-QGQWfvrAgLwayVXwdeg_BRVxo4DcTc2ow8mLUKxEdaidTd2kZUipZMAL1JMKlGULP9ZZHxZyG-LDJTXMa5FaGFF0V5juUqROhfaUf6E2tdrp6omixoZd2hq0ohj--pzUxRnE7HzgwRzbIr5-LjfYsS1CEMQuP5g
      name: sops-key
      vault_url: https://sops-master.vault.azure.net
      version: 90784f2986de4514934b4d1f682d3e59
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T03:30:17Z"
  mac: ENC[AES256_GCM,data:jO2JFkMSYmoZt4cZMA4BcGm7CGHGZDFwBzvBpuWOdGhhX9Qr53Kwhf1dYAuyYD5m6DYK7cUR5pQhSxc3o0T361SnbuxL8w/VSPlfFeu6qoJC7JaEsB7ixcKkH4a3dxivJTW5FssO2WqGW3J9Q7Q8J59hnjwjKvRPnns3XVi20G8=,iv:WyhIW52kdjrVYM5CiPNEty0fx/xNBUxg0IorgxxXiug=,tag:+K0yGe3gGasiin+0HF0RuQ==,type:str]
  version: 3.13.3
