apiVersion: v1
kind: Secret
metadata:
  name: artifact-keeper-secrets
  namespace: infrastructure
type: Opaque
stringData:
  #ENC[AES256_GCM,data:1GhNPjP0rfT1rrkCs+X7/Bl8VLr0BpjSs9hHXzwhaA9tzjUztxinlaw+xQBMmPVX4nh/SNnzFtDu0w==,iv:igi5SYVR6ThPNq94dVR/zypis+MJ6nmxPtPszOpbKtc=,tag:YGA02n0KWT3PFz8uYdrjRQ==,type:comment]
  JWT_SECRET: ENC[AES256_GCM,data:f7dQxqm9z4fk26WrlLlimg8RjBTu8YsXnv9Fr1s41U/dhRt7G/dwzWNVOYF2p3SXdFcHS2PxjRWHQHwh2LKG6w==,iv:eamKiHp6wSmDqovYqfrjYhoYdJHYI2aUrQ0urQFukCM=,tag:tQmqVpGaMYiMG5Y/3MwYNQ==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:jkrH8KBadLiNgUMuXjxiVwlJfeEJo/lYkcWCNZRq1gH8Uqu5HzaSz/TO48d0nsNJCfmbWsWXMgf9DH8iFxc0cmPPQibNF62cannZvof8RZoucBljE+Xu+YnqPb/bfxFi5WhqKrH6h6exmq00OpW5/DEX0T7T3YcXmte+6Ek=,iv:GKyz9oG1EkBzoPeScJvVLsbJelkvhhJla+XZMn/JscY=,tag:mbzgFboggmk8STEBiGF3Gw==,type:str]
  #ENC[AES256_GCM,data:DCYopIWXnGwdExZouYGLWrO7BuA+pYKWZBeoKVFNQB7K7vbHXCMfSQi94fr/ZSg+Gyyw0KgFQi4yew==,iv:Vm+X9Wbd+qdC/lLaA0pcluCZ3W3vAk8kRt/2yWu5VoI=,tag:D4LKP0d8XvEZf7LDbiwwKA==,type:comment]
  #ENC[AES256_GCM,data:tKx3nwwolytUSlAn6wm/DwaCBSpYsfZWW4qB+yCZom5KnKsJSxmxdQvTLyPpJjUSUANtkLiwW232GqULIN3nLCjUFyIx5k8tJ40g4MEccjk3gimtdDYaF/6rUW0=,iv:XhVgQvJ2TTGkYneXgDnLilb08NCuxMA2/Ss7hF911RY=,tag:V9IN5K8zqpREuCV8HzwrcA==,type:comment]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:ZunaOJxgvQpdj6bfgYcHqrQSn1jIjL2HkusehdaYmoi94N3i5EpwdKA6QWhLtZ5Z,iv:PO7P+s09SJub085shgJqO9RSp2zGVJw8xGK+z0cJNp8=,tag:YKYbqVd3D5QWi7KHAo6jOQ==,type:str]
  #ENC[AES256_GCM,data:I+ohFcvHrlgoW4zlgaxgdYVta8hDTen2bvBVLg==,iv:EYu3p2ZYXb+JousnA+dAqOCQsfgVkSGHyQbraHuYLZk=,tag:1TtSHcHTg29NB8++C6uk8Q==,type:comment]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:T1EDN8JgJh5jd5+sKOE3Hm9mkmU+p8EClzEjq/4Qn+dEaRMgO8ENhw==,iv:/bJK2HbNdcH/1wtI7DEtYIsHEnUFx1um/UPJ3Xjifp0=,tag:z9P5ZVYHmEOaxBMv9yEooA==,type:str]
sops:
  azure_kv:
    - created_at: "2026-10-09T05:24:38Z"
      enc: DjxFtBRZT3Jc39Tlwt5jmxaQ12Wo0ercmPWccop35cAHFb7kp3SxICPZwDzacef2os78G0_MzUtBvRYMAr5o4EKlpqgIvT7irDoCF5nt0BafG6s7qlqqv1oHJmOXOQCDB5O5ioagdpvDY8mvSniJvjW6CI1XUGgxpTDH25aXFJ-hqg-D3u8UqxUkhpZ5cb-XmTuW4lNweEDYwceVJZbzxXNPqR6JNrdXLwJyTxOd2uWOHTHZVVwCETXbLGGmTyKfmJ2Cq3Jxcg2YGKy3PjnTQq73xoE0lMKhaB0xgxXz7tv3sQsmF7Ka-DxuSKiiwy1gXa8s2obUgaMWQJfcsnqofHPDi352-9yH49zPmS-EnIiTGUwVIEcSXwhQeWV3T_1rZaDxMKW5bFeP6phHaZuwr1K_NH_6oKICOTR3JBYRxGE1YPyUWa7rI4vsk65HdjQJ-HXfMpg7B2-j_RIbOTbr7JLgLesRWXgSVcQ07zAcS1TzptZF-yX-JYD4PbJFDw9PgU61slrE7nyGYGM84_CnbU3P_KzAuYPnJlU61u8rKabbRic2B9FtEGSG6u52VjhuDNDd26zx8xvxH_BR3isbt5k4mD-XCF9UQMdBDCKcdTPHuqfhuuMkmE3FaYWuFPnrbXgb6fFuo6lFpn-PTgKbv8ecBbqoXKcIv5Av4baRG3g
      name: sops-administrators-key
      vault_url: https://sops-administrators.vault.azure.net
      version: 37bc81e975ea4a2194985560d066d52d
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T05:24:43Z"
  mac: ENC[AES256_GCM,data:sF/pAo46w+zES016IAh43A+ozlb5AW5ng4p2bG3/Lx0IKj+WCVEgLcVWFGqtK/XUcp1OIIb1memjR6G8MqI8yRcHV2P3hp5kUxMC1797ES+rY3xtRBv5LGeqJkTe/KzKRQM88WEgvVOqQJy69GXRnxzRdEJUnw8zObCW6WreVF8=,iv:rGXvD+UQ61vPGzlBw9Gury7CuBwnNr30UUNNG0Um/gU=,tag:B/xyH8+8RuO+MpvgPYG0nw==,type:str]
  version: 3.13.3
