apiVersion: v1
kind: Secret
metadata:
  name: artifact-keeper-secrets
  namespace: infrastructure
type: Opaque
stringData:
  #ENC[AES256_GCM,data:0GF8mon9NJu63mAbpHrhp5iEZ7InU1N2SPoFUVeuiYKVsWy8g7K1qC4sSjewqzjw7/XIAptyq/TiLQ==,iv:igi5SYVR6ThPNq94dVR/zypis+MJ6nmxPtPszOpbKtc=,tag:Pap65mfcI02DKq+UdxuIXA==,type:comment]
  JWT_SECRET: ENC[AES256_GCM,data:J+9adUlHc5r9/hre8GHKckMPPHr8Dn9pHMQ3JXWNvLl7qcwgO9pTUCWUUK+Wueg6sbnTo9L0X3q1RjqEvGmcbg==,iv:eamKiHp6wSmDqovYqfrjYhoYdJHYI2aUrQ0urQFukCM=,tag:6/Sw8YjUn79lBfCfEnYlFA==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:5GumO49SvIRcjUk6IKbqzYzMZIvJ82s8BerR5rUEuqiEBx+BfR6DCmG/ywKGwWMPhosf4JqkgzLpJ4Qz18FCJjaMckDsECG8MH/rbwjJjwvAIrBj5THZnukX4UFq/FfLkk2a1RAXTpooXaWRgvEucccdG3/AOUYikFlrDs4=,iv:GKyz9oG1EkBzoPeScJvVLsbJelkvhhJla+XZMn/JscY=,tag:0QL+4eyeYmBc8RTGt6OMBQ==,type:str]
  #ENC[AES256_GCM,data:/gdYctlmSyGNpsY3vzEZX7qA927TTbUOKF+tS9i+MA6EVAyRdJ2Rc+ACTRPnzEIiy1S9PgMgNvu3Ig==,iv:Vm+X9Wbd+qdC/lLaA0pcluCZ3W3vAk8kRt/2yWu5VoI=,tag:ZnAu9zDn93LaTeIZuwiWaQ==,type:comment]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:PnDkbejcLQrNWeVLBD0NjU+XqVz3T/Div/6ze0ebF0OvrBy+GugiPhiidqZetowU,iv:PO7P+s09SJub085shgJqO9RSp2zGVJw8xGK+z0cJNp8=,tag:L3+Yqn9VnyrK6R75tgXlXA==,type:str]
sops:
  azure_kv:
    - created_at: "2026-09-14T14:50:46Z"
      enc: E54qrNC6molxBLr5bB5Hx1cv_hytkA1aKGyjdGnbhCMMlpIw0GQaUE5G4EaBUH6ebHLmjojHQv-myY4CNhUwOEjdOneoljx9mwZxO2rnrnMRrw6iY1Ene3xYAmANN0uxai_jB3bSJSJcandsa-L7POoHOsYxM-t5zcV9LtpFZ5Nf6UxCshUUIeS17TM_5nsCOd_5o8Xg4KADgqVTAFZQfDbRKT75-uppT0Q7VzIayY6jRAbf_svNrZDt0QmFgjmwxKLumcNt6STVhqHEZ5MSuHl2eBmysE61SVBvCsViHEj15bN9CW3Lro5SmhckRvf5a3mG3HKkciWezfC--bWlAw
      name: sops-key
      vault_url: https://sops-master.vault.azure.net
      version: 90784f2986de4514934b4d1f682d3e59
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-14T14:52:10Z"
  mac: ENC[AES256_GCM,data:J6A0cRmzgoRg/Mg+SpsAYlFIMDwSrWb9nVTJfPkYVmBRtIxrUMgZ+Dym2Rwin0u466Rx621mQet6k1rei1pUOS2OHwTx22H8z5PZEDtGjHGrBqbFxrzlQeyRhqtWC/9ADdx6mpq08zZZ2wjirsRGaAdm9ftSpKVNiZY0vnTp6N0=,iv:SPYjCaMtRVW64enfKtE4JZOkBBTgPqA+MY80HLmnuLE=,tag:/lLoPxEge2lfLAqXgPXBbQ==,type:str]
  version: 3.13.3
