apiVersion: v1
kind: Secret
metadata:
  name: azure-oidc-secret
  namespace: staging
type: Opaque
stringData:
  CLIENT_SECRET: ENC[AES256_GCM,data:xbGuXHgKR6dPzhDk9G+AH/wgsVo34Ll6uTUYMnV1egMpXgZfaFrSEw==,iv:eHOnJh/ap2sIbNDcbuwJ6xNp/cuXLG+U88RnZKE1IAQ=,tag:MBALnwTu4sVbcPaCZbE+0w==,type:str]
  #ENC[AES256_GCM,data:QGgHceljmFrOPt+fixoe1w2ee6S5RN/R/RGjHd8xffWZO62pNEUmTosKmudV/VjlXygaEBF/q1+iHKGGDVIXTg==,iv:YoIVuSj8DWbuffjPheOTV3zc9vcLYrZ5yE2Md7HlLhA=,tag:kAal13VRqayBEUvPhd8KkA==,type:comment]
  SESSION_KEY: ENC[AES256_GCM,data:YNvKEc6N1zsTwRFgV2elWTBopEnHc8G3Z7bpsDZ23ptbZE4sO9Tk4VppFGMuCEmScgYORuAVhd8LjEXe/vjHSw==,iv:q/qppAVQne8/otHBal38jdNsvJUNeVEezL8DreuF80M=,tag:lIarpspL8XF9t0ffDQjPtQ==,type:str]
sops:
  azure_kv:
    - created_at: "2026-09-27T16:35:11Z"
      enc: m3iz11JRHjg3fz40n-vq8J7VmPouOPskru4k-8T8roWmlfltoNk2O4xxtntyZCEKSeAQq5XT5CgV9dsENrcqs8S-TrtVNQexQavmDy5d093C4AhSOXWnMddueIFquFKwZalwdcBEvem2R1k0z0cNxF6WDoe7kKu5Z_Qt1K5V5mP5er4QOY0IZEdzIit7o8udJOkNTwTxS7n_EfZbLWhDg19mZTSYm0KaJ86SfH3OrmLjrpRiQdPDWdJo4XuvuR1-o-13C-2-qO5UIOr8pN8cJqxLACq9xrGB0Ek9SyTvejtLAqgUXQIJQHbUrI254ey8GaDXr9kydM-bNFQS1vLnZA
      name: sops-key
      vault_url: https://sops-master.vault.azure.net
      version: 90784f2986de4514934b4d1f682d3e59
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-27T16:35:14Z"
  mac: ENC[AES256_GCM,data:dYvJFkz2daivUc9Zt9nAEIdlTkFVFvhZPAdCZr73PT4ts5fI1kawl3HcubENy1gh+64E8LMxBfh1WWdUTpluFWyw/X3hfyH+3ng664IRX5ZW1lvirfyTtFTZ8D+K7FYXnqspzi/F93mjZauy1/DQMZ8MsBONwB1wd4ca2Nj42bw=,iv:9/lfRXIFtFOErb33Tx3CfIe0C+cluQ3udQUhtFnsTrQ=,tag:XD2DCVyfNGUXKAA+nIWgfg==,type:str]
  version: 3.13.3
