apiVersion: v1
kind: Secret
metadata:
  name: redis-creds
  namespace: infrastructure
type: Opaque
stringData:
  #ENC[AES256_GCM,data:qqdlh0GZhrm6zMA+Y/+kfTNxw4BM8vtmiTPMO352A1sHWSHbv/b7A+1PQe1VApJC/kPBFedixUXlC/8=,iv:3tZlE9A73Erz7zfE0cssL6RhnpETostbJjack9lllRg=,tag:KHIujJlGbslkZnTvhMOkcA==,type:comment]
  password: ENC[AES256_GCM,data:AqUBeDaDEJWxjqFvvlh5v4PSnAJUv3IrRvYe/zA48GM=,iv:U3gZcptIp+7UsCO1xIK+evE1H6kLog5woZ9y6s2VKPc=,tag:Z+7y37GDpSTGF6XBQgc6Nw==,type:str]
sops:
  azure_kv:
    - created_at: "2026-10-09T05:24:49Z"
      enc: dvMAJ2Mf7eEhZuYXDMPQ3A14WTyih3aEGTkLlecr74ogXUS_cfBfxoOucxsCITA3TAPuOOm9BbhADMcWJZCVT-G2Gxosr7nHcByCUXhTE4b5rLkr5a_ZXXH4LgZu6QJlzTb8FEMZLNFt9Fz6OKpZXF0sYUsZsvdYoTyaEBUmH-xMeHHXh75lRpIb2WfVCcB4xAwC8nfSWgDZEzm8CcaxnRB1mBX-u68BPrdfOvQsoueskqMwvpso0LlOG8EHfbzOTYFccilRGLGLF3OsJ6wXDT9dCUlx9Yhu5usIutbag1hyCzHUhUrnzUOAx1j8-7DqQiW515gK1lWLu7vsB61npQAYJZAIwM8ttOMtoz1dEN7kOt4H8CThR_5eAH3JfyewX3DUxN21H-BAw4c9Xm-Jqb0VVd1ULGx1BecGlCRS1yViEBfSDUqm_0PL7-a0D6DZkUZcwCCLC2Ew1w543csrDZgZ_9u4BZAf3t7iekzokl4b2UpVPnBIhu126kmKofZMAId7e2WePrGm0dWhBaN1Drpiu7IJH8gOXZ7VMvCffWrBuakCW5XOFyhXrijAjoVP8aKPGUmNtXelCwLw3uz0vIq72SaDLV1ySufE6khTODbCKTmlfv9LeG9S1_f6_PIuUopT6p3l1_oqyrHRh92JwAq-bouFld5j5159uPXUPag
      name: sops-administrators-key
      vault_url: https://sops-administrators.vault.azure.net
      version: 37bc81e975ea4a2194985560d066d52d
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T05:24:51Z"
  mac: ENC[AES256_GCM,data:et2FqvGU0K3a3mSDFHXLvhheIuHn/up0pa3S6Cglm2M9+oPhMXfxxLv+g5uBk6J28HKluKOrrLYnlEm47nFbVIpx+4A1jFysgYfCwIP0U7+ZW75tsjh1eQs2T/D4okGK+mUqy5QUd6pgMEWdBzHM7r4TuYkceWXxvT9jpiNJLCs=,iv:ovo7XA/jfA+RgR14lQQ25BNSVi83yfbrDDQSI9wbByY=,tag:BG5RcftSY8MiBZv/tqtEKA==,type:str]
  version: 3.12.1
