apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cert-manager
  - traefik
  - artifact-keeper
  - middleware
  - postgres
  - redis
  - grafana-prometheus
  - loki
  - fluent-bit
  - azure
  - headscale
