apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpn-coredns
  namespace: infrastructure
---
# used to update secret state created in state.yaml & persist tailnet identity
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vpn-coredns-tailscale-state
  namespace: infrastructure
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["vpn-coredns-tailscale-state"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vpn-coredns-tailscale-state
  namespace: infrastructure
subjects:
  - kind: ServiceAccount
    name: vpn-coredns
    namespace: infrastructure
roleRef:
  kind: Role
  name: vpn-coredns-tailscale-state
  apiGroup: rbac.authorization.k8s.io
