apiVersion: v1
kind: Secret
metadata:
  name: postgres-backup-creds
type: Opaque
stringData:
  PGUSER: ENC[AES256_GCM,data:CkIv6OBAWFH/pBMu2TVc,iv:Nao2pQghhlgGtVG16hrXqaAZ6/wIq0ENDywQ1CttBHI=,tag:DGaYI8l5j40mZCMonmu/0A==,type:str]
  PGPASSWORD: ENC[AES256_GCM,data:P0c9+c5q1WOAbFAr1B0lIdnB00ZzCBDuauINeTEuxf8=,iv:71Op78JgD70ScglsRjjHCq1T1aJbEMLSKmVTvrakAbI=,tag:9vTViSNE96EVJiKNJ1oqag==,type:str]
sops:
  azure_kv:
    - created_at: "2026-10-09T05:24:47Z"
      enc: Ps2v7VWwE6n9mAyc4XaKSLhyN0FEiPuZBh-tkPc3N8u_G5rtTFK121GXclf1SLEV3kFVudy9Vzke1FfW5wuPTwE-1ck6izlQZkja4IoUoxDqri05ZJ7ni6xAzLy5hc21LprDJclMzrYzFZNJUlFEhLBkNnREdKzkxbGcrAvU3X6m3bSL3C6kvyh3O6bzYjNGo7D8dXugikXlApnXUCzYfphiRX0Fc881fQGsArgvn1e25VX7TPJkZervQ2iRfq93MI0obtFhvqXBeSAHWmfdSvUGkouOs5YOYyJrU8RBBNcea9fQZXxExC2AQj8ad19LsqyLIDN-RoXHXlaIZ93ilnU-QovMwnaXudiIwZw2zUJ2InyCIHR6letDFcLA4j9Q-7Lj28QfpkrpAD-9834VZs1fnag7LDm3wd-Mhd75aXcBc-G8JlCtGdAGn4RX032anetylxLW85a_6pT7elhviOw1pQUt9UCkB-fLYTJANd8fWX-nzRuK7jYJdzxjdpT-WkvnR0Rk6kfkelD_qfCfjk8NdD0Wkvjzxo77htoEjRMMYidwxkrtl_CmT2-S9lj4CP1SNUgI3HD6H-J6EPP4xFWI9yaSChCT5U7eZyQsoIZLGVUSHsw1CuW2aPUvEoA3DXesIVoFsebWAmA_ny-2KtCyUQuEF-ojiOEA9f3G4Fc
      name: sops-administrators-key
      vault_url: https://sops-administrators.vault.azure.net
      version: 37bc81e975ea4a2194985560d066d52d
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T05:24:49Z"
  mac: ENC[AES256_GCM,data:5fZnFp4AF6oQrmM9WHlPXBVnOl7RBswD6Y5g0EjT0F+S/OtnYmwh0E98oJMFuwWNRKVB4y4k0hw5lCWV4eGIWkRKQzyfcpp+SBzza2nUhvsALLE/FyKTd4qE1jTAYXuDX5o98tUu9LOWPIQWJyyhIB6d8C3GtEDqnI4Cs6H4/rA=,iv:FIH7EUOx032Yw6U8vCVvHQwhOIi/GdiKOiOAqVp7BUA=,tag:8DQBWKSkVq8Ao6Omtm90Vw==,type:str]
  version: 3.12.1
