# override per env in application-<profile>.yaml

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        # add beans and env
        include: prometheus, health, beans, env

logging:
  structured:
    format:
      console: ecs
    json:
      add:
        sha: "${app.commit.sha}"
      stacktrace:
        root: first
        max-length: 12288
        include-common-frames: true
        include-hashes: true
