apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: infrastructure
type: Opaque
stringData:
  ADMIN_USER: ENC[AES256_GCM,data:R67KxnCdtQ==,iv:LxltGRXjdklqF6S/J6K4oCa3Blo9v4NSzwg96Z+HwUs=,tag:oG4a9FbRwF8oFkeW0H8puA==,type:str]
  #ENC[AES256_GCM,data:gqKqVlE4FKwn1LhfdT+jgfComi8ClgOrkOBRPMs0On5qUaI9mUvhQd3EWpMlsu8AycIQimXVNd88fa6aAA==,iv:0RBmOG6OB84KN6hWS5SQanN4dzoP1bx8XLqoPa667f4=,tag:xTk+9niQxjMqCMqLatSK3w==,type:comment]
  #ENC[AES256_GCM,data:VCTI6fuZd5o9apJwriUHxMSuExofko26F9cM4xMr6laS5cadeRc8f6fx8+SXLmyeuXCfp6fP4+uzXC4l5HEtmQmf3iA=,iv:IQtk5bWR7KCx3PuwL+tErtqv7kdRRC87FXBLEe7wY78=,tag:S6H/k9x0a9BDrYf/g5clhw==,type:comment]
  #ENC[AES256_GCM,data:TdTlk6Izd+fdeo5Hqqc=,iv:vnfCV3ZAk9J53doOLYvlE9lt/8MPoW3EbCYE3ElQhSQ=,tag:OEzy0XcxYvxFq2pyFUpAkw==,type:comment]
  #ENC[AES256_GCM,data:g07zAw==,iv:P7CN0PbIrz2eLWoRe+6MzEtSIlK9rAHRdEw8h366dyA=,tag:73lPTzDysTULB3AjGz2FLA==,type:comment]
  #ENC[AES256_GCM,data:wzTySUR7qpD8bHeaqokVOYRA6TqszfYm3HCPDCtVZ8FD7cb9G5AaYxU8wvF+7Ea4OxDMUd8jtpVsT4XLmVgBVVcXKMGPlFJMAQIfrpPPktKEgQumoyMGnZo6BAdA+Zu1/weymaPsTaqrO2SKptNRm3I6vNTCAx1DFtqputgaAikIGvH1dHgajXfz,iv:4VmslMCm9SZA2MH6MxmZbI2rKVmKe7v6H4i1LQUiVqw=,tag:L8/FHZOkan5N7jyhWKBjmA==,type:comment]
  #ENC[AES256_GCM,data:bp8Dzw==,iv:a5xzKh03G1SU+1Za8bsRjb6r8e7LmZHvR/v9/NxqYd0=,tag:IGPrmuXivBgdyUYRn+lknA==,type:comment]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:CKDM4de+iKej7NKYMWvgGQ==,iv:rwKrjjzFKxm0s2sKK3+Hksbk2mWp9jfJ7f3z1mRwRok=,tag:bSiKMdBaC3jXNSbPjvRBAA==,type:str]
  DB_USER: ENC[AES256_GCM,data:cg3n/uDw0eoYmA==,iv:Z2Yov3ixZAwKbN16f/UeTpPF2uImz+irHwaVHLoTSJI=,tag:87uZGJGd6WmcCJnqjB1U1A==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:MPOyxW+DHMcjW+LFRjEqNKGBWF/+XgoN67Iysz3uaB0=,iv:lquMGSmlK4GQ6oEwdOO9xgUoXZAW79/n+k6iC1YBpvU=,tag:fu8rReree4TYz2mh7uLayA==,type:str]
  GRAFANA_RO_DB_PASSWORD: ENC[AES256_GCM,data:P+03rUhMb+bhuJ+1tgVYAxqf14qIZKjNfqqOsk2bBf8=,iv:w+xL2rjUmlo+B++bQJ4/hf7tbnRoFyKhN7aczNLeulE=,tag:GRKNuU3mfWGr9FuzzGftSQ==,type:str]
  AZUREAD_CLIENT_ID: ENC[AES256_GCM,data:b3XVqQCFhSVeN3eJKtLf/r3L+Acl/u2JiBm0DyLc6Lt5lxNE,iv:LGSKx1A+ccH+m6Zk66XnGt+W5UEAS9MP5AzzoIjKKKI=,tag:utL/F87rEGnd1icLY3l/ow==,type:str]
  AZUREAD_CLIENT_SECRET: ENC[AES256_GCM,data:on9LsxrvWEY9a7fygMn5SfnPWzbGmEq2d87RY5X67IdQqGnURSi1pg==,iv:bWV0OudEciBxVthk5746EZkuhXZyGemA6VphceWy4Gw=,tag:yjxQfloYIIx6x8TqoIb2LQ==,type:str]
sops:
  azure_kv:
    - created_at: "2026-04-15T09:56:11Z"
      enc: XygGioSZehBYyFBnBQmv0zgoHSHdy2MqFwS1diAPPattf2847noFlTQIC3ZT4b-7wFezv6cPsEH2tHrC23JsxDzHm1sZisJVVKQmUSNIuuz20C7tCyiwmEImItCW4aVM9nfba90ibZseH8x75QIIaz7uTgxZuDpZgS7BsdLYDeCY96tCIreSyDn6LHtBxmaKsLh5WBu1n4Sgsp_QTJmxnlerRvdG96MuZrC9bh3KZHKcoqco_DcoM2ClBjpWclIJxaNS475cd6Gtjcaktf582cc0_JRTFAFTDC6dFcllx5PQvcxD-JJxwT2gQVMxbMJTY6EPltjDKPzEttWEl7_xPQ
      name: sops-key
      vault_url: https://sops-master.vault.azure.net
      version: 90784f2986de4514934b4d1f682d3e59
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-12T21:13:40Z"
  mac: ENC[AES256_GCM,data:77XC0INIzOzi1126xaPb1RyCbmBoVT7ZDPyj2tu/roTTiCsegic8EJ2INgY9+gyJ70na/l8CCuX5qUuZLj5zwZnBCVQiq5HxGJJ1D0iyswMKmMy0BvtcIa5Yh7kwQSPZJDaH3BVqhu3uYSz6DrDyd+9UQQPWlQ18RiwNY/lEIa0=,iv:EM34q3W4ppdujG1m3/3wfscp+RIFj/Vfx2anW9C6GBw=,tag:msbcaMf7wI5HIHVE0M0IGQ==,type:str]
  version: 3.13.3
