apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: infrastructure
type: Opaque
stringData:
  ADMIN_USER: ENC[AES256_GCM,data:50UqQ9PmCA==,iv:eoZ7J6bXV9kvVNbai1ApOlurtBt4DS3hnNGsIX887vw=,tag:rIKMxP0pB+jMJE+SuhgeHQ==,type:str]
  #ENC[AES256_GCM,data:V21+NwEk/wRU4M7FLed2unb2dv3aXMfOtT+ftxez0DX30jFdCMmnF+LM1r4SOK4I6EXU3bYWQ9YiLtqULQ==,iv:hLQljpNM8Wj+wLHt+JsXbxzWlb4oQhoHRfmtovYGk8I=,tag:aOe/CDYblgojAnJEK43ttQ==,type:comment]
  #ENC[AES256_GCM,data:mNRvyvOf/iyGxpfS/uSpKS0jZnnTBeYBjDw0MnhGSLVU+KiDQftlyqiD97EoKL44v0eO82jZmMQnMNPmOii0OU/hw4o=,iv:vJtLLrW6rBlX98ohQ6XccGmtji0t3BxWu8887J161Dg=,tag:iZnkT+3s+YBd/tz1tltVKA==,type:comment]
  #ENC[AES256_GCM,data:L9uCzBeKHB7wo5HOt+c=,iv:uoUblMpz7RQmBXkyvtN3Z05lPbTpO3Olhh0JGRYcZyQ=,tag:3jI6pwIIusyC+qB3NeWwFA==,type:comment]
  #ENC[AES256_GCM,data:B/GfHQ==,iv:vpTjDZy5IHfpFeZ17dxp9dz0Gzm9W1SJJgG8BRsPoFg=,tag:OCWvIpDw1/PsVDWpqumSsQ==,type:comment]
  #ENC[AES256_GCM,data:MtFfr57c+XRayH/O4jP2EKKxJNvV16SzWCRZpucB5VnxZAOit3c76OaEOV5Piy+lr6u4YeRz5wNhcxZuSsIi31NlQSBGZZ4fOA3VfWpQI6+NCROgeNuH57pvsqYT5r7O6zx3tTEOl0mjZfWgCYr0FjomICkhqdDRvcfik6Ookv2fXR/Hs4a/yqim,iv:7pTCLxZ6mpmq7a44PjwIcjZv1p6vOj/rXOilOON36l8=,tag:ZOAGbZRfN4WfYtYeCqfvGQ==,type:comment]
  #ENC[AES256_GCM,data:1TTuPA==,iv:K/yZx41wSlmvJ4jXR33WBqmTcDsIS8rf7qeVysugEmc=,tag:wnByRhS1Z7/nOvmCRwFF/A==,type:comment]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:uDsv8Wt/K5JDXVh0x0FcDQ==,iv:/5JCBUZlkQqoX6H/29sznyN1cs8qh5kQtd+6rtrg/oc=,tag:jY+tfYNaPlvCBDfSR8QYJA==,type:str]
  DB_USER: ENC[AES256_GCM,data:Whw0/nQp3EicTQ==,iv:WrfcmKbraXP9JTIXoiSH8GnvwLwgiWU/ADiyCyKkgnA=,tag:/MgCXLPuIjaCwMdLCvlDnQ==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:PNfigujvFiePVkQDHxFGO2rxrIL5fmesSTgfEFQ33xM=,iv:ibhRrBXRNDsXTXXEghlvHczYOndHsvmFZLFAKufGCDc=,tag:jy3YtGIyq0PDulPrQwaljA==,type:str]
  GRAFANA_RO_DB_PASSWORD: ENC[AES256_GCM,data:1ZlKVWuKuoijMn3nI91/vZ0NaMzMVtGTI8LQo3B8wgA=,iv:IxCHLOfH5YYsaumUJl7G584anGvqhpB5rFNLo3hSYMk=,tag:kPthJ8fBv0NTXNrbU7HfAA==,type:str]
  AZUREAD_CLIENT_ID: ENC[AES256_GCM,data:khWi+orx6AzA5gdV0lp64FWmK4zHoFGFeWJ1jbZKAlseE0yI,iv:OKNnRIEGHr4vKftVR62JCkvmNZY8FyV8Ft/Un+R1TUE=,tag:68DUrEZDWjWt9xwcoZyyrw==,type:str]
  AZUREAD_CLIENT_SECRET: ENC[AES256_GCM,data:e19QlEwfIqyj4uXF2tFp4NYeOtguFbPS1O0ePUD1fpcRKLbup0mgjw==,iv:DA8iA3s2lvUqs8nrP7hbqnBDx7IP51UIdznodMzsMrs=,tag:ZQKq90w6MfSEFlzry2K1fg==,type:str]
  #ENC[AES256_GCM,data:0FMV6MkxBdx9JkQ8r4iYWtaDEC5Lwi9AgrlPkA==,iv:UFM5Od8pNmWWNSFK7bUl3eGWxyl7hPWz1TeOoetRTZY=,tag:2c/4sk+yH5Inr2+RBZw6cQ==,type:comment]
  AZURE_MONITOR_CLIENT_SECRET: ENC[AES256_GCM,data:UoYrY3H6ZOUP608kaIOdajFAcusqofQE1J3K2xSdKrnHPDKHwV1nMA==,iv:ALvayMVO1cP97FW3pjODyqZUSS4l/T1pjrtct6jhC2M=,tag:CbGxfxE3Fj2vq+HW5Ypj6w==,type:str]
sops:
  azure_kv:
    - created_at: "2026-10-09T05:22:02Z"
      enc: WlqLk9hX3CE8tfyocE2N30lPyH2SnMQHbRhUEw6hmcvu8ceUpu0nlYXJQ37Kl3YVeAJNh_57RdKv84ZLS0mpF8fX0bqnRY80Zv5GNeqdVQ_e1656vr8kfy1s8P2H00OVwZq2rWonXN3-pjKdzmIC5mnzrPn6fETXvOQUDrS5lQJJyNNw9tOYIfGdrY2_nzCwCsF9J7YrmeM4Zrbuq_D9qA60A8xgaRKG5Ko77sWwGhrzqk-_aMYtMyUBFeLCZCuZBQrjeTx0oAgVYjY86SS6310Bi9PvzIDq4aN2NnR0AxQsWCKherjpSyPEL1WkUH3Sh6ebqSSymohVQGqcFbTlT6broUbGdE_RxLsSXnLcixdQGXSv-vZSzlKpT9fHx_lx9z9RlxE5dTWbvM3i7Iex3pBrWViwcBVoKmicGOPrrhG6PNfo-__tOgETB0BeTmvo8G3cXkQ0YtHvbvRP_k_yoXY5FdpCfEWp1cjEtqY5okWUWgj75Aq1Pkk5PThCDpMHszhNFYQCovzOGEPSRK2Pej3KQRl6wE4iXkR2w7B6dyCOR3LKz5N_62PKK6gVFTrYnbWmwOE_D1U59j5nmvIQclZbpN3VBgLIEkO51egAtvssUBTLm3UlD9kMqsXxb3zu_EtNVxiXUk7TSPk4GB39LJNQizJw3B8VQwZiwgIsfA0
      name: sops-administrators-key
      vault_url: https://sops-administrators.vault.azure.net
      version: 37bc81e975ea4a2194985560d066d52d
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T05:22:04Z"
  mac: ENC[AES256_GCM,data:tGTZdhIPRH2Qqew/UhsI/7poIrIDSRXOhBM6EFbgvHMKql1MEZc82TRGDIIcD/SM1Pf0XkgDR15ge0i3FFNXUdibsI/SHzqfh6QrBaY3Fvqan/vpjrbk1iK96YNnf9RGThLhKyy1DmOLxJFUNfsgZ4ULj4b+A4GZ5Uc0kTruxX0=,iv:ieatU/IE+z3h8xSRhG7i+lLmdwyNQXNzDLpEdlwPdY4=,tag:lnqk+ncXpST+00NahPkM2w==,type:str]
  version: 3.13.3
