apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: infrastructure
type: Opaque
stringData:
  ADMIN_USER: ENC[AES256_GCM,data:R67KxnCdtQ==,iv:LxltGRXjdklqF6S/J6K4oCa3Blo9v4NSzwg96Z+HwUs=,tag:oG4a9FbRwF8oFkeW0H8puA==,type:str]
  #ENC[AES256_GCM,data:gqKqVlE4FKwn1LhfdT+jgfComi8ClgOrkOBRPMs0On5qUaI9mUvhQd3EWpMlsu8AycIQimXVNd88fa6aAA==,iv:0RBmOG6OB84KN6hWS5SQanN4dzoP1bx8XLqoPa667f4=,tag:xTk+9niQxjMqCMqLatSK3w==,type:comment]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:WNIKl4LoUmtih3wyTadbaw==,iv:vEA2mS37BpU+LbNIr0L7bOLb3CGWjez5b8+Xd8MCVJk=,tag:T8JZ5SB/WBI8DZE9thGOTA==,type:str]
  DB_USER: ENC[AES256_GCM,data:cg3n/uDw0eoYmA==,iv:Z2Yov3ixZAwKbN16f/UeTpPF2uImz+irHwaVHLoTSJI=,tag:87uZGJGd6WmcCJnqjB1U1A==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:MPOyxW+DHMcjW+LFRjEqNKGBWF/+XgoN67Iysz3uaB0=,iv:lquMGSmlK4GQ6oEwdOO9xgUoXZAW79/n+k6iC1YBpvU=,tag:fu8rReree4TYz2mh7uLayA==,type:str]
  GRAFANA_RO_DB_PASSWORD: ENC[AES256_GCM,data:P+03rUhMb+bhuJ+1tgVYAxqf14qIZKjNfqqOsk2bBf8=,iv:w+xL2rjUmlo+B++bQJ4/hf7tbnRoFyKhN7aczNLeulE=,tag:GRKNuU3mfWGr9FuzzGftSQ==,type:str]
sops:
  azure_kv:
    - created_at: "2026-04-15T09:56:11Z"
      enc: XygGioSZehBYyFBnBQmv0zgoHSHdy2MqFwS1diAPPattf2847noFlTQIC3ZT4b-7wFezv6cPsEH2tHrC23JsxDzHm1sZisJVVKQmUSNIuuz20C7tCyiwmEImItCW4aVM9nfba90ibZseH8x75QIIaz7uTgxZuDpZgS7BsdLYDeCY96tCIreSyDn6LHtBxmaKsLh5WBu1n4Sgsp_QTJmxnlerRvdG96MuZrC9bh3KZHKcoqco_DcoM2ClBjpWclIJxaNS475cd6Gtjcaktf582cc0_JRTFAFTDC6dFcllx5PQvcxD-JJxwT2gQVMxbMJTY6EPltjDKPzEttWEl7_xPQ
      name: sops-key
      vault_url: https://sops-master.vault.azure.net
      version: 90784f2986de4514934b4d1f682d3e59
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T03:36:32Z"
  mac: ENC[AES256_GCM,data:o55n3ac+IOPDW9MznImuXloYZadli1190pxydvPJYq9sPMXhKJQ9L1GIng6RuGgy27ceLiOy/5guryIt6x83A5xrgYcd2r8cGstMlBxL2W6y8IfBU+9ZWcIB8xU8IuVGdBsHfXvnPVykQQnrlwetrgMXUBjI3zbmiIrZTEJHeuA=,iv:JaAP33Y4JbiMq/hQvDVP0Y5C/Bh5xnaWly1Hc0hNoPo=,tag:Zn1PY1dAWvFYty0I2lqbsQ==,type:str]
  version: 3.13.1
