apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: headscale-ingress-infrastructure
  namespace: flux-system
spec:
  interval: 10m
  path: ./base/infrastructure/headscale/ingress
  dependsOn:
    - name: cert-manager-issuer-infrastructure
    - name: headscale-infrastructure
    - name: traefik-infrastructure
    - name: middleware-infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: infrastructure
