{{- range $repoName, $repo := .Values.repositories }}
{{- $repoResourceName := $repoName | lower | replace "_" "-" | replace "." "-" }}
---
apiVersion: repo.github.upbound.io/v1alpha1
kind: Repository
metadata:
  name: {{ $repoResourceName }}
  {{- if $repo.existing }}
  annotations:
    crossplane.io/external-name: {{ $repoName }}
  {{- end }}
spec:
  forProvider:
    name: {{ $repoName }}
    visibility: {{ $repo.visibility }}
    # enforce rebase org-wide
    allowMergeCommit: false
    allowRebaseMerge: true
    allowSquashMerge: false
    deleteBranchOnMerge: true
  providerConfigRef:
    name: {{ $.Values.providerConfigName }}
{{- end }}
