apiVersion: v1
kind: Secret
metadata:
  name: azure-oidc-secret
  namespace: production
type: Opaque
stringData:
  CLIENT_SECRET: ENC[AES256_GCM,data:t0/A8m2TSV5cW990EtAk/BNmEAd1RtFZizNsaTz2STTuEywxUyo7+Q==,iv:4yIfHcYWvzBsEwhJPIUBpYeGBk7/E8Y/Yr8VVb+ZkC0=,tag:k9htVl9RRO5mtjAl2glXGA==,type:str]
  #ENC[AES256_GCM,data:gJiYVk/Oqb2Q9+fkMxV/mWFfRl0dlK1wJSFYTtXPBC/5Ud20/XsWBy2T+fHWHMcUDsHuV5CBf0UK+mbPca6MNw==,iv:Ohh+0nUa3HnmIH5ETI1ZpSNJGezP/dB/e3mrJI4tymg=,tag:OUUo2RVvjyaTdO7eufVaqw==,type:comment]
  SESSION_KEY: ENC[AES256_GCM,data:V7DxiaWmzFkgc6O14xN5hkmaN/CGz0juPOnZ+dyxLd9AU5k8vrlhGmwCnSPM8Tg8aetB8RJCXGzHyF3oOY/R0A==,iv:qsNGR5AOpYkxozLeD3h1sf0SAlcZNZJ3alCv0uuEsqI=,tag:VFcOLMMHOU8KbUEd2tjWuQ==,type:str]
sops:
  azure_kv:
    - created_at: "2026-09-27T16:34:35Z"
      enc: kSVdQn1Fkge4sprKJ66elpVQzi-KtWenD8WZf3oqQOO6_dbpfSggrWKeKwJ7oVVQ9BOEL1npzyrQ0-1MS7OZ-_swKFBiEIsvORzR-oIYnK9gEDKsf_1Sn7VVGczL0FcTy8N7Eilt1Oj7Zv5-Fq5G4wFWRuSxAJeHC8TCupBSHNuf-of04UiBxPx0jFqvdET8-lJhGsvpJRQG2HXhLssu3eyfeHTFT6iCK70uMyYjH_Y8mCzthFo9y6EGdeul8oJyg4VF8IUjlmVEpM6RY1Iz0D9QIgJ6axRsCSXxhdOz5J4tSKyaRR3ef1ReIe-glLnyI_9x9eDukalCTnHb7x8t7Q
      name: sops-key
      vault_url: https://sops-master.vault.azure.net
      version: 90784f2986de4514934b4d1f682d3e59
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-27T16:34:36Z"
  mac: ENC[AES256_GCM,data:MFijPNG05t6hGSOV8PYUbM68eZy0zLaVsff18nlx7c1vKwQJqLhWoJby6SXtKBnbHgaGHV5/MYJKC+0VDrCYbx27N3aZtl4ZjuMs8OxNJWttixNwuD1TS5tECys5niYpE52J+m+z94obIxV7IzTgsnnqJO9dcx/cDsHLX4zMIHU=,iv:stYFdStHwbNoVseRH44GzetoxCUHTMHi3a+EXCZBlw0=,tag:Ry8yC1fFptPtcwozrrVvKA==,type:str]
  version: 3.13.3
