apiVersion: v1
kind: Secret
metadata:
  name: gerrit-secure-config
  namespace: infrastructure
type: Opaque
stringData:
  #ENC[AES256_GCM,data:kky1uVWuLAbpRtZMTbgF56AK9Hnz05TLqDEiTq8Gwf1wTAN3bQ/SN+zG+kHlorTzDtXuyCeqOIPBJ/TZqbFmCxk=,iv:g1PPYGUJfvliIvGsoGXieX8v7Txj4MoxcSnZMDx8t3s=,tag:uj1W5P+wcZDtvEQaN1oSVg==,type:comment]
  #ENC[AES256_GCM,data:kPhSYgfsTKmyB8YKGnWJU3Bq2HKmixUTVsKlGiBcdlg47dwlcpeRfG02H3SR5pL3XL3PkFTHlGmZZ6XbngSKuA==,iv:D2IA8pVR71XwMSHFvzO4lPk48I+60cDJTG/u6g6RcfI=,tag:O4GPZUZKH2SnBoeBODNeZA==,type:comment]
  secure.config: ENC[AES256_GCM,data:3L7N6bSwQHIYCQDyUudComkWbE6riS+xRJbwJJgZsQevLDW5i4xE+Q+5qvz38b9ZqM2LaUju/j4wx4bU1AQBsy9Q4K7TUIXWG/+v06rjl8254mbC8vW98QpAOxG4fD8Rz47neC+JsA24iSE3fsi2Zs8R5gB4Yzkhkhj3ZTMWlQsNGJQnjT4dzhPs4FvWmN6de52ar2GmQO8zjfSrKMFtEzemwoJvSxmkfXR/dKyC2dkjZsJnv0THdiPFDjyPYofPtnInUOb4S/mtN0ggDe/1LrFmnovtFrZlPRL2hklSgmSlF55DrEmwS97IyARN3TN8PyYp+c4oAL3Q2awg8xXRLpw0G00ZTmjcO7Q=,iv:cqguRtH1w2tcox1um3O50p+s2PeISjwVkxO1C05M3Pc=,tag:JTT7FJHzOU/4nbavLrWDYA==,type:str]
sops:
  azure_kv:
    - created_at: "2026-07-04T20:54:59Z"
      enc: EIqFzexsCr_9keUWLzG3PzsbmhqFnpsu13SFy8txG4-zOh2JpsYnSjFO5CTrtUXHaBH9N9SKd8Spwm18OSW3gXAUTPJPKFm0cBEsL7Yj6O1zgpTIL2pzMPJmPVHUOGAS5DVsDJ_y8mN44_F4KXCL1gUnLiowUSCrwbuxEGPAwpkX3AkxO0EOmEaOnAIp3nCQQ6q5fQapxv0lhwEXNTVtwc35a9IEorHhOTPLBSTvbYa9mlqAcBcslg7ptgeeSQXSuySK7hU0LKC8Ot6NW0MAXpG_9QLw5T9L_xaMJ3IdzVP5ByP_ymmB9q7ezKAQghzAiBfVF4KUY6h12JFfaNvTEg
      name: sops-key
      vault_url: https://sops-master.vault.azure.net
      version: 90784f2986de4514934b4d1f682d3e59
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-04T23:26:06Z"
  mac: ENC[AES256_GCM,data:x88KTqOErCHFsrU0/bprXDrNXyz4Hi3iTfsPorsyWOCdd0insfneWVKI29ZI8BR3BUrxKLOEMMZAlrLpgrD30mmbHlw8E79lHjfJiOdV5lnZVzcQ2S0zfqq4TjcX1ZNF2fMEtBGXfrnSKKeugjoS914PfEnDiROYDiw3js/yPMQ=,iv:/MI/+7MTOkllqX2uOV0328azpuvzhjMv8nTADgq/hJw=,tag:pyYzLdJBMUWfvEOjcUwYSQ==,type:str]
  version: 3.13.1
