apiVersion: v1
kind: Secret
metadata:
  name: gerrit-secure-config
  namespace: infrastructure
type: Opaque
stringData:
  #ENC[AES256_GCM,data:kky1uVWuLAbpRtZMTbgF56AK9Hnz05TLqDEiTq8Gwf1wTAN3bQ/SN+zG+kHlorTzDtXuyCeqOIPBJ/TZqbFmCxk=,iv:g1PPYGUJfvliIvGsoGXieX8v7Txj4MoxcSnZMDx8t3s=,tag:uj1W5P+wcZDtvEQaN1oSVg==,type:comment]
  #ENC[AES256_GCM,data:kPhSYgfsTKmyB8YKGnWJU3Bq2HKmixUTVsKlGiBcdlg47dwlcpeRfG02H3SR5pL3XL3PkFTHlGmZZ6XbngSKuA==,iv:D2IA8pVR71XwMSHFvzO4lPk48I+60cDJTG/u6g6RcfI=,tag:O4GPZUZKH2SnBoeBODNeZA==,type:comment]
  secure.config: ENC[AES256_GCM,data:TRx/E0tVjYcLQ646N3foe5AeG3yuq0eK7kNJRQ6d01MB6oqsmwcwDrPNVjCCLoAY0xEO/U5sH4wrqcxR3aPHhwr7RUJ907dyGzXbLvVvMn3e04L0G3yexvXFpk8U1fT8r6peLfQ4Bo6vJJ0rzbUa9CCh7QLVynu+duLtfDy2cfUl1ZF/HcYI8XWQtbgXojJCZGpbAUeXLEhg9/T533JAOj2F9/2wwuocIVtHWfl9zL+I7lPO2yn4n6QZzt1URvJepZYOZzG9/Edxfzc4ksz2zXXedE/pdLGeO1NzcYhGBXItq1KRWe59xv7tzpD6veyo9Um5TVHnP09tC3olM7b+mihA4zzcuZ+K/T6PswvZmA9JBV3F7RTwUlZlqg5gNTIGbNq2nlkx1J8PiVC4HjOLHkk=,iv:qtVEuZbm3lhK2IXqKOWRgDGxw9WgcHtG13fEi7PIO7o=,tag:ma6+iiEbx3TJjilqngEIZA==,type:str]
sops:
  azure_kv:
    - created_at: "2026-07-04T20:54:59Z"
      enc: EIqFzexsCr_9keUWLzG3PzsbmhqFnpsu13SFy8txG4-zOh2JpsYnSjFO5CTrtUXHaBH9N9SKd8Spwm18OSW3gXAUTPJPKFm0cBEsL7Yj6O1zgpTIL2pzMPJmPVHUOGAS5DVsDJ_y8mN44_F4KXCL1gUnLiowUSCrwbuxEGPAwpkX3AkxO0EOmEaOnAIp3nCQQ6q5fQapxv0lhwEXNTVtwc35a9IEorHhOTPLBSTvbYa9mlqAcBcslg7ptgeeSQXSuySK7hU0LKC8Ot6NW0MAXpG_9QLw5T9L_xaMJ3IdzVP5ByP_ymmB9q7ezKAQghzAiBfVF4KUY6h12JFfaNvTEg
      name: sops-key
      vault_url: https://sops-master.vault.azure.net
      version: 90784f2986de4514934b4d1f682d3e59
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-04T21:07:24Z"
  mac: ENC[AES256_GCM,data:bfus+T6/3i3ENVrMihRJd6VWXMuEuW0kTjLChwrc9F6LA0Ou5vmFN5nviDZx8yKrgQxnv3DK5TO52VkHKBUpCDsm94xw+/274clkbqmzy1jxeR9CRTD6Xrq/GYwsp+yejVg2osXqBx+Oht2oSTacTH9aAva9LQk+0uEbl/tWzNI=,iv:sWVPYDonbRel+cOODpdslerVw014MMWy7PcxLyz2mPw=,tag:bDHJ9p5RVJz//bIf7/Knsw==,type:str]
  version: 3.13.1
