apiVersion: v1
kind: Secret
metadata:
  name: gerrit-secure-config
  namespace: infrastructure
type: Opaque
stringData:
  #ENC[AES256_GCM,data:Vaq7+KXiKLeLg6SBNI5InQarW4ZgzJYVuG9rH/uZudLTZB/wOa0MQbvdGc2wFGKJNlhU+G1YhWmvdk+jGBYJJBM=,iv:g1PPYGUJfvliIvGsoGXieX8v7Txj4MoxcSnZMDx8t3s=,tag:H4mkdspez1fiEpJs3KzVPw==,type:comment]
  #ENC[AES256_GCM,data:aRcD7xZgjqMkWYgCa6ibFz9k7/bVsM/995MzOZ8TbtQoeP2qbJ0iLTkgzbYBjLX7PvvEjrbi/pvPLnHUuXx69Q==,iv:D2IA8pVR71XwMSHFvzO4lPk48I+60cDJTG/u6g6RcfI=,tag:DO3KDFy0sbrbfSJUejT2EQ==,type:comment]
  secure.config: ENC[AES256_GCM,data:m5wT60fnb3M+r4C9f5tbz6EbJNNH2/3zrA43snf5Isyxji/N7LoOi+jAWLThIUmP0XaYcr5um0WiZpXI7n9KMYUh7cAKsMnoY4y21gBuF+xK4lUI/d4YhZcy5FCT3UzDWDXQYSFNkAmJcOJSZ8eztYyOuCjrR1JZR4O7aIaXcHMy6odUrOjkKTihHs4z4FwOVWQ+2n74mgfhPlJPv7lEysF8mlcidVv9c52Or0zcFvqbThFwI3rsn6G4iHqi9/tTHPeH1uAf8LEh6yxSM9dIzw1DPguzUpChRES1GxcoBKQEwyJ/5I73ptL0azjkuI4PGjzR9KIS4Dl6xbClcbznyK9ZshlRfJBg4Sc=,iv:cqguRtH1w2tcox1um3O50p+s2PeISjwVkxO1C05M3Pc=,tag:lC/4EaF1ViHwV1cNs9Ng8A==,type:str]
  #ENC[AES256_GCM,data:cwztwVHNLNeClUUKCbekHd+VyZIEKwJp/wE5Jv/RFk+/VU/FJb0idkYzg2VLga01ax6HcH7gmmooI+Vms5eGFQ==,iv:nUt4ZPzEaIjQx7lp2//ogriFlTUKXXJs3t5v/pCNwRE=,tag:VzeooJBaYT+64gwCfiqiBQ==,type:comment]
  github-oauth.key: ENC[AES256_GCM,data:R6PDqVcJRyZhDhN2CIaHR0D4wtTCzGrp1q+hCDNdO7w=,iv:GFQS0pQ8TsUS9+xqYJrC+VaC6wuqu/KcCNZOqqWWEe4=,tag:qjiwv39jFrwlRdw+bJz5Jg==,type:str]
sops:
  azure_kv:
    - created_at: "2026-10-09T05:24:45Z"
      enc: MtbdGSbrCkzH7L2Xu2iEgEuLuz-iaQ-1MDSlslblbwQyctpX-zWEwgNyPXC-_kB-HUiM2_to2zpPSfjcW1N4E48fBzzxUePp71s5QLj_hwamm0MI67KMzWaWRsrD2UQPu52w23u3TpBJXo42WwkbXr3WykQ7a7lxTnnZFSA5GQeGGjbx3laDXX-3j-WZZ8Ah6oPo7FNay9YKobQywJB-bQ1mFGcqtT69MiBMB3pdlyyMXxlYbF3bhNvh24bq4vrOo3oXhJk3VtsDW9oiSQEeJW4bwcSntiKt8hyXzxLKN2czl8umGQ9nnoWq_tlqT4qn5BarEp4s3zdANh4j_mzlc-BJvEZvCTAhJoJw6yRtSOMS_epPYfFdQEa8dCi7ygN-_QWCAi3-SKYIZYImDbDM7_Z0t8YYcoQVFPPQnpbWZ8xHOGxNfmdXs66wtgOm8cUFD3JJmN-b1-x4BDf1FCx6WvSgNs5ttbW4eUwmvlDws94GZtesC864D2qz20Fq3UyKn8zpW3E_tSj2yidPpTPOAqtV1xUIluKThZoqJYp4jnTzX7HyJ_pLqNYYORdKThTYlDSMtv4rzlTy0xle2kjjTEQkbab5Q9vcwHuHfLq-PArkmxrOaumpFeQgGf19JnmV23xejeEQUpDYgnO8Mc1Aae5oVQdtZzU0bYiAcuR9tnQ
      name: sops-administrators-key
      vault_url: https://sops-administrators.vault.azure.net
      version: 37bc81e975ea4a2194985560d066d52d
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T05:24:47Z"
  mac: ENC[AES256_GCM,data:t0nqqXcMmNVFNboikjpACaj5E2NBQu/39rAyQFU5bPy+y8rJvSiAygKlMehPOkte/9fk5BXn+gnKuIG7o1bMvN/R0pAme+ko/gZ3OCt3KCOmCyDr3PJmdrWNI5nc+fLW4xy4jaUkIxfhZQmDOiFcaC6XvDOY7cnXtRH2Fnnq/0Y=,iv:MhByNiW1CpopOZmVOV6a1GBtCVWFUMd8AdytoB/CnUo=,tag:Juas3isUyQmgb1a3hkcpgQ==,type:str]
  version: 3.13.1
