# shared defaults live in base/base/patchats/application.yaml

server:
  url: https://stg.vpn.patchats.patinanetwork.org

management:
  endpoint:
    env:
      # /actuator/env is behind basic-auth (ingress-vpn.yaml) so this is ok
      show-values: "always"
