apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-patchats-vpn-tls
  namespace: staging
spec:
  secretName: staging-patchats-vpn-tls
  dnsNames:
    - stg.patchats.vpn.patinanetwork.org
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
