apiVersion: apps/v1
kind: Deployment
metadata:
  name: patchats
spec:
  template:
    spec:
      nodeSelector:
        agentpool: stgpoolv1
      tolerations:
        - key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot
          effect: NoSchedule
      containers:
        - name: patchats
          env:
            - name: VITE_STAGING
              value: "true"
          envFrom:
            - secretRef:
                name: patchats-staging-secrets
