apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yaml
  - deployment.yaml
  - ingress.yaml
  - secrets.yaml
  - service.yaml
  - servicemonitor.yaml
configMapGenerator:
  - name: patchats-spring-config
    files:
      - application-stg.yaml
commonLabels:
  app: patchats
  environment: staging
images:
  - name: patinanetwork/patchats
    newTag: staging-1526313

replacements:
  - source:
      kind: Deployment
      name: patchats
      fieldPath: spec.template.spec.containers.[name=patchats].image
      options:
        delimiter: ":"
        index: 1
    targets:
      - select:
          kind: Deployment
          name: patchats
        fieldPaths:
          - spec.template.spec.containers.[name=patchats].env.[name=VERSION].value
          - spec.template.metadata.labels.version
