apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-hello-world-client-rust-vpn-tls
  namespace: staging
spec:
  secretName: staging-hello-world-client-rust-vpn-tls
  dnsNames:
    - stg.hello-world-client-rust.vpn.patinanetwork.org
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
