apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-client-rust
spec:
  template:
    spec:
      nodeSelector:
        agentpool: stgpoolv1
      tolerations:
        - key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot
          effect: NoSchedule
      containers:
        - name: hello-world-client-rust
          env:
            - name: ENVIRONMENT
              value: staging
            - name: HELLO_WORLD_CLIENT_URLS
              value: https://stg.hello-world-grpc-client-go.vpn.patinanetwork.org,https://stg.hello-world-grpc-client-java.vpn.patinanetwork.org
