apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base/hello-world-client-rust
  - certificate-vpn.yaml
  - ingress-vpn.yaml
patches:
  - path: deployment-patch.yaml
commonLabels:
  app: hello-world-client-rust
  environment: staging
images:
  - name: patinanetwork/hello-world-client-rust-arm
    newTag: staging-4f0384d

replacements:
  - source:
      kind: Deployment
      name: hello-world-client-rust
      fieldPath: spec.template.spec.containers.[name=hello-world-client-rust].image
      options:
        delimiter: ":"
        index: 1
    targets:
      - select:
          kind: Deployment
          name: hello-world-client-rust
        fieldPaths:
          - spec.template.spec.containers.[name=hello-world-client-rust].env.[name=VERSION].value
          - spec.template.metadata.labels.version
