apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-grpc-service
  namespace: staging
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: hello-world-grpc-service
  template:
    metadata:
      labels:
        app: hello-world-grpc-service
        version: "N/A" # replaced from kustomization.yaml
    spec:
      containers:
        - name: hello-world-grpc-service
          image: patinanetwork/hello-world-grpc-service
          ports:
            - name: http-web
              containerPort: 3000
            - name: grpc
              containerPort: 50051
          readinessProbe:
            httpGet:
              path: /readyz
              port: http-web
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /livez
              port: http-web
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: VERSION
              value: "N/A" # replaced from kustomization.yaml
            - name: GRPC_REFLECTION
              value: "true"
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "250m"
