apiVersion: v1
kind: Secret
metadata:
  name: tailscale-vpn-infra-preauthkey
  namespace: infrastructure
type: Opaque
stringData:
  #ENC[AES256_GCM,data:kucfW2FnJXWfyw8pvY/Qq66AbwtXILLQOCk60G5Vm1U2ziA3Qu8Hx4CjzdmZ,iv:vj4oU+VaHstmuKOuN6/UOJk0Ayb/wc18hN1enPS1ZwM=,tag:qOyrA62rpc8fEGlSVt0QlQ==,type:comment]
  #ENC[AES256_GCM,data:xBSeOJaYe2VhlMGloSsbGGYuDF8LHhfor0jjmXJnxz9KP0yZvi5fWQ==,iv:be+aFjQrna/kA8yfCe/muPv3bMHYDeeMZyNHGvunP9Y=,tag:rIbaVflNz/L+rvmWNjpzfQ==,type:comment]
  authkey: ENC[AES256_GCM,data:GxG0I1wU75v9qPGdrmyF9FLM6OtY14ZVuEq17DvsHczTZLfRpwDPkdj8ADd43EfplLaq4cwZrhvzFdvJu0Aduwb2Gtv+xkq5x1fEpwePna8he0NTAmFCqw==,iv:a9BWZ7txpfWWP8Oml62TyoJfrDTa3o2DD55CdaXU6js=,tag:7j18qTCi+nObs9xBb7RHZw==,type:str]
sops:
  azure_kv:
    - created_at: "2026-09-10T14:49:31Z"
      enc: h0AUv80pwsAEecERRRwY8qfhiGBEkL-zB6_Hy4WGwK6a5sr-3O55t1Z1xGf6ak3fpkHpG6_EBV7Gy6CpqmnQGXibCpv-OXNu-oWV3nZAZQL6cdQ9Sv8-Q_JIhNoxRnCahLsUShG7rMr61WfxAl5mUIsKrl8kB66ygNEqD-Ml-6K3D6i1eVufu7Y2uRADOowZzABWFituIImUJI8-cm2cvZEyxrOInl1VJxwzoK7Tcfaf8XVw4qfzXP-e07pTpEpLW_X6WQ6_BjKojsFIcUsBl3zmbYfcRYiclvJ7r7Fiip30F1JEElH5Vfmw5BUWQyF-9Gvo2K10k7e0XS6hu-324g
      name: sops-key
      vault_url: https://sops-master.vault.azure.net
      version: 90784f2986de4514934b4d1f682d3e59
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-10T15:08:09Z"
  mac: ENC[AES256_GCM,data:wJ4ClFK5pSJY7C3mGi0HkEPRuAp94oKfPQfOTcs9j19fHIdkxQ3IGm6CB3VIsf2ngwU5+aMfYxgSU7vSAWFhWXAL67F3hAAq3Ctq4C8YkKyXaAPR8sR6eA7Myy5Lg3Ugf11KvcRiV8CrdE3QEo1Zf6phxeU2XjUMFps8Pj+6AGE=,iv:zG9Qj5dU2SC1JZ6SQgeHOwb0wL22RU7u09MysneKVDg=,tag:0/jcUj/booNjv9O1xagCmQ==,type:str]
  version: 3.13.3
