apiVersion: v1
kind: Secret
metadata:
  name: tailscale-vpn-infra-preauthkey
  namespace: infrastructure
type: Opaque
stringData:
  #ENC[AES256_GCM,data:4ALJfqSZg7f3ytnL/boW0hFIood6Q5HUIuh7cI3aINgouYgotP2SOUICBqB8,iv:UmjhjhM4abj4tv28TtsKnxu8+Lh6YIAbI2PIK30Dtmc=,tag:VBFEZKFOqv2YRgBzU/VfFg==,type:comment]
  #ENC[AES256_GCM,data:T42fC/12d4k8WdXOTMqJdKs7jjWByxH0O88+a7pR5mMCVDLeC4FxAA==,iv:abxjGBVKPCar66ML86oc82eQxsPX1bQ6gAPmuScsQuc=,tag:Xz4xp225NcNqCXbNBpi+cA==,type:comment]
  authkey: ENC[AES256_GCM,data:sAvwffETKg+KvYrFk6bAxXVELL8aNAcmuH+R4oQOjlMuRwuWh96w9+Rvl4H3gudeuPMG8keQl+I359Y4LUkRttw1j2HuYo8jKHrVBFBMtw+XTVlT9z1CrA==,iv:Au8jwhGLNC414t/9kVRoOzHLnfOFzd07dE7kry87zMM=,tag:XP1HVD/+vKVWaQ2+G4NCCg==,type:str]
sops:
  azure_kv:
    - created_at: "2026-10-09T05:19:26Z"
      enc: KdwtuV-X-tyZtbucjvIgMouQjdPCeepEpq8RTIz_Mf5rilaBGC-7qhg4PYUC0ToKbONeJsoy9K0--vkQIBfMQsdsuuF14yH74dn2MLwY6ApVVMaU92ib4c7_W--wtvnrWIRVOgA5u0ZT-0LnE6c_6yEEUeRMb_Nu11RvSe1I_5wcBfQs_qWoquAM6u30omsgYQWf_lMsa73R48pmFptN74mFEgXbfBEzdw9SXcxv3SgSfsqchwoeK3tH0VNlJp0P5F_vddvlszmLIi5HH08ZwS-6NiCEJUH83foZh132We4p5713-bd1lWAcL6Jgr7njnJievOY0I7GEWcoTFHDFTy_-zEngPzyzKwUPJNi1hbvj8vdRL4xBpIqGXtEQRtPs-fVBwonjbairxmbAbNss7L9XeIAbCbRvmZ8RhQUDKpgjhjPCngnx4Tfws1M5r8GMougK5Lj5-QI0Pcbzunc5r7Ph7noZ07pWUASaoD4iVcuCsn3Rg2G9c_2mBSvmtZOpsxUBfsASzZLUkgDimCpGFcSOeQ8Ehu64wWpIhHBRVABt_8KShLMOAKLqCd7rOvBoF8byYQno_O-t15U9aUBlLbrpcoBRf_8r5OzQ3K-JbV-6UVqrEwBAK8xbkynN9P4gMFCw-Bc0wRIdOl2NCKKHzlfvUTbXNkhk3no41ioR5Ew
      name: sops-administrators-key
      vault_url: https://sops-administrators.vault.azure.net
      version: 37bc81e975ea4a2194985560d066d52d
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T05:19:29Z"
  mac: ENC[AES256_GCM,data:gh7i43CKkNgrou0JVtDza9JmdzMOTAy997A8h6GbY0+gTtwU7Xmw/ocuCE1CiEC8wYQd/UsTCHeK33YxR00qIdt624u4q/0rpa2cNzzW9Lm6ttKJGrngvXkQje1ztMFuYqsWL/ri0Xf3ocRrCOknhmLXvYWy4JOrZ9PZF2cuiZs=,iv:7ctaku93aKazcuSCsrHKsicDMJHTWMxC7DGfciAaYbA=,tag:v8Jioco2+4/YGxWCKluPcA==,type:str]
  version: 3.13.3
