apiVersion: v1
kind: Secret
metadata:
  name: tailscale-proxy-infra-preauthkey
  namespace: infrastructure
type: Opaque
stringData:
  #ENC[AES256_GCM,data:8KKKDdTIYhag/sj08C/jY4/hgqSgA6D4SYgcDmbT+BQ8ULLoDo59g31AsSgUZIo=,iv:PUMbRhD1I+LUefDfyfiUHvTUSB4Z0vBmEWv1Vx6NVxc=,tag:/MxMyPqNaIw5/NKH65mPzw==,type:comment]
  #ENC[AES256_GCM,data:AXP7Ftcd7XrJcXbUImyJvdPkVHP2Q+JOFI5FVaprMgGkOSZ/FPT4XA==,iv:2yZkpyQAuFggYPaVQR0npef/gmSwjacXkp54zFVuslE=,tag:Npy8Z55khdacigezpNTXiA==,type:comment]
  authkey: ENC[AES256_GCM,data:3qmc/iWn6XB9RTwDn1ga94FFTJiYiZMUYm/vo01wIZ3hvnXxPr/yDiWJQI0mx4qjlzTqlcBUtnViAosQtpyrQICtgiZ83m144VrFmePwHd+kZ3jhLAFMOw==,iv:9oPQZK3s0vQKuL2yc4SNzOzsvCDix0GXWxjGH6PksVU=,tag:vXAwHFnwS2xU8GNOXKlPqQ==,type:str]
sops:
  azure_kv:
    - created_at: "2026-09-10T06:31:19Z"
      enc: R9nrP_IogHq0GcV4Wgnkiu4ub4gJ8NiXcyh_4OBwEBYdMvGaYIQsBImA8LU6yY8eBxw3FztAsTk88UCQT6rzvjlX_VDJBLiidiC05e_pIj8Ij8r_qDZJXtB0EovlE4d896uwYRoJvuofoiHjSqKQ2JEkQd-yk18zm7OHR1vDJnFMi1BO-ki80Q59c-jDdGaHd337G99N67nO-p-YFG_Skm3o9m8n7V20ukX8rG-G9ghqQi8MvZFy9WbMJBiDwRiRbfKfQvajZQJCi1hmy6Y138DRAiKRzOQiWfm4xoF_7ca8jNY9A5KfNo5-kjajihVjNlX_79_9YN8mQTDzQ05BNg
      name: sops-key
      vault_url: https://sops-master.vault.azure.net
      version: 90784f2986de4514934b4d1f682d3e59
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-10T06:32:19Z"
  mac: ENC[AES256_GCM,data:HmeEGxmxTa4MgZX3S+LDA2iOc5h7KscJ+6L28Tj/7SZ416DVmUOaNHMrGyd1IgI4zIgGeBqIkvUKwu3u0xdbOXNGyT8BCYnccrZPJ5ZMi/kiuNunTtxqPitZegwKhP0MWN8TTsoMydcdG95aCQBB5tyUysY8uotRLnpuOVIz6a0=,iv:JdJ4G5n+gg4EgwWA8xAFrh+PI7cxfbj8y+sYndW4e0U=,tag:dxXPwCiUgCKaLjy0stmRzw==,type:str]
  version: 3.13.3
