apiVersion: v1
kind: Service
metadata:
  name: hello-world-client-go
  namespace: production
spec:
  selector:
    app: hello-world-client-go
  ports:
    - name: http-web
      protocol: TCP
      port: 80
      targetPort: http-web
