apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ./codebloom
  - ./codebloom-standup-bot
  - ./middleware
  - ./azure
  - ./patchats
  - ./hello-world-grpc-service
  - ./docs
  - ./hello-world-client-go
  - ./hello-world-client-rust
  - ./hello-world-client-java
