apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: artifact-keeper
  namespace: flux-system
spec:
  interval: 1h
  url: https://artifact-keeper.github.io/artifact-keeper-iac
