apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-client-rust
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: hello-world-client-rust
  template:
    metadata:
      labels:
        app: hello-world-client-rust
        version: "N/A" # replaced by the overlay kustomization.yaml
    spec:
      containers:
        - name: hello-world-client-rust
          image: patinanetwork/hello-world-client-rust-arm
          ports:
            - name: http-web
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /livez
              port: http-web
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 24
          readinessProbe:
            httpGet:
              path: /readyz
              port: http-web
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /livez
              port: http-web
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: VERSION
              value: "N/A" # replaced by the overlay kustomization.yaml
            - name: HELLO_WORLD_SERVICE_GRPC_HOST
              value: hello-world-grpc-service:50051
            - name: HELLO_WORLD_SERVICE_GRPC_TLS
              value: "false"
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "250m"
