apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
  namespace: infrastructure
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:eC7TmHC+Q44=,iv:pwV2MTJM2OxK2KEGgzxXBqU1rBHcSZ3I82DZQFKmtZM=,tag:eWBOpb11JHAsto2NPxcHQQ==,type:str]
  #ENC[AES256_GCM,data:iKMzNP0UdNONFsihRl50cqmkBxmu+yuzw6RulzpHaIY43lGLk6fHKfIbFRcd3M33uGXidD+UQcOrHg==,iv:49UBh3WIvMwIklGYlYqSPg7P3uzrDG6CZlDEwlveROs=,tag:zuI/YS4RrgzgwcTPI4h/UQ==,type:comment]
  password: ENC[AES256_GCM,data:sFb6oGHZ+Wa8E6R2C33Ncmn60+QN45Lr5p/snPOo178bO9MFxqnW1jh6PXbH0Q0M,iv:Hhm9BoeD3gVeTvS4e3b7dSE8E6yk7udqOGWTD4CtEPs=,tag:+LpJcpAkWoRWT4W/pwMdDg==,type:str]
sops:
  azure_kv:
    - created_at: "2026-10-09T05:05:40Z"
      enc: iPqcLxH7Ue7GR9lJtasb8zSsNFgvyJCD7ki0O2_wupiiuAN02tnM1oEbmokiKAy5CfjAxnSNF6yf7H_WCM7WLWFiIs2jLgsbREv89PNd8BoJGhqtTIJvwvLfsL4HBTRy5QrZ9hkRR27uPjMsqrn9ZDhqREPCL-iNJ7TV4b2ScaMcHLOIGkkPmHTzLPNZybjnvWa-tocMajtlc2Gw_qZjup8Cd85x04OaW4xeID5U5k_jVjSsI59_0FtUbcYE5mQSCMYMO7gKF8j3jE5_gJXVgXmw7AV6PkWiw-dpPfe5wVVjdN4ZIbcY0rt1C2ju0Omc1lNGaJ1gL0gJsPVZmM_3e3rOndjQDdoe008zfyMlOH4RzlZpvP0Qx-ByxjvAQEEdNvcy5u7InkqcOBrhI-auVeRUdGPEqKqpSSjAFx8pGXNLhkHBqlHwLG9NhWYjMmkZUgTeulsfcG2WNSgk-MJtgOm6Clq6Cz8wj1clcKlh8Fp3NHcHytqTMV0lAMnC9LV-kcuYCz9ozFnH2Kcns2dGXni9PmauY0m1-z5x2WT6Dc7bKEPcyAe_MHrjc5EY7zVs9onbTr1B-O6los0iunMba1-l6WJ1POPBYeTJnhbEuyAC2FgnrinB-V0f4BpndC8vK8xCw2H1lrY5wLpphFUN8HR4FSwz0SRob9M_ukjbxeA
      name: sops-administrators-key
      vault_url: https://sops-administrators.vault.azure.net
      version: 37bc81e975ea4a2194985560d066d52d
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T05:05:43Z"
  mac: ENC[AES256_GCM,data:zHP8b2VcEO0v8itGGyAIY4GL0fuIHWhc2JH1LASFMnisd3RO4N5JdAjVGaR759xmNGXrBxI35iAf7xN8eu7Qnb7XUJpvc6M1Dvl5dXVtDrSjAxovJ9bK41C+QlzezS8fGrXs7SuRI0Z9y80Ftx8PjwxbaFXaeFvnGZ1gnNjlkFQ=,iv:RpXXoqla133iOO1Z5hme2Ne0vTWh44E7Tt3dFc3Ve9Q=,tag:rUDdjByEm5EUMUPPgnSR0w==,type:str]
  version: 3.13.3
