apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
  namespace: infrastructure
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:F0KAis6rCPQ=,iv:wCxfLwInhjTjdmb6qVIK0BBy8iZUspqBtvZ1cQKcI2A=,tag:4vp4r7jqFicymDzPCm+OVw==,type:str]
  #ENC[AES256_GCM,data:i4LchRYs0EBvfRh2ICu7temoAqfxTogLxCesWTbNCERi68JnZHHpDHJnq45uzZrOjTdlu1pV9+eNNA==,iv:46wyAD76uzzaExkb1ZQEHIVDXH2nNm6NDqsJ/6rrDNc=,tag:ItaYypFAqijgi3xpP0rYVw==,type:comment]
  password: ENC[AES256_GCM,data:psA8KdFOQmFRqIlmyyC7R0CkyawTK5HyrBfP3LvDxrvfbAkXUzGq+eZrE+qQrJ78,iv:C9GlGI2rk4T/SNJNSOxJ+Mo6VbIuV0GWCa1EchaoM+A=,tag:yfph0Yg+B/9AOuchpwdv9w==,type:str]
sops:
  azure_kv:
    - created_at: "2026-04-15T09:15:50Z"
      enc: fJ7liqMjBTVe5aJVEPgNQfrpM_GRnD-X-k689qM2r_ZVizFJW2xLJY-HRe5bkDL_DXrHzUTIjkI28cIjJmt3mWfi95uEtD3IIiESZ7cIhoW-68ovH3SFohLSpUiKRhZV3BSg1KfjSd7uqfMF-HgFOReFuZzkaZNkPByExN7WjD9JJLBNfZ3D-ewu0rMLRWbWq-8h-8JgyR7GE26zPQ8cwL53EF7YdhskUQ_gmYmFdft_3UzfKEP8LY0VlUvl4V50m4MMQckrudSBzbsQSlcYh3BNoRCDDTaKKXaeL-itBK8hrDRCwJ-ETW6j3oIUnRCLmyOY1O-PCTV3h54mtHn-Hw
      name: sops-key
      vault_url: https://sops-master.vault.azure.net
      version: 90784f2986de4514934b4d1f682d3e59
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-08T05:04:57Z"
  mac: ENC[AES256_GCM,data:sMKZ/RcuP9aTXjosTWezpku0i2oHXUSTdP5eZo8B4sUYeaxxoS0P2RL+wnjbux5IgjffD4t7apyLOga4fHHe6wlmRaFvd8FC+ObIM1VpkBP3fv3O3tdP5VfqM7GlcierPkrSss7QSxRWGVUOq8zXaov82zOee/A7GTnkM5DM680=,iv:TLZ08lktnELDqM+2N8jffmtC4jkg//q0tDl9JfmnnLs=,tag:ygqWfjephP3ODGpD+uxIAA==,type:str]
  version: 3.13.3
