apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-client-java
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: hello-world-client-java
  template:
    metadata:
      labels:
        app: hello-world-client-java
        version: "N/A" # replaced by the overlay kustomization.yaml
    spec:
      volumes:
        - name: spring-config
          configMap:
            name: hello-world-client-java-spring-config
      containers:
        - name: hello-world-client-java
          image: patinanetwork/hello-world-client-java-arm
          args:
            - --spring.config.additional-location=file:/config/
          volumeMounts:
            - name: spring-config
              mountPath: /config
              readOnly: true
          ports:
            - name: http-web
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http-web
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 24
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http-web
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http-web
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: VERSION
              value: "N/A" # replaced by the overlay kustomization.yaml
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "256Mi"
              cpu: "250m"
